"""Entrada de producción para Render.

Mantiene las optimizaciones y reportes validados hasta V108. V109 agrega en
Análisis Comercial > Macro el reporte ejecutivo de ventas Año vs Año pasado,
metas mensuales, tendencia gráfica y repara la carga/procesamiento de los PDF
de ventas mensuales. También reprocesa una sola vez el historial ya cargado
para que Macro quede listo sin esperar al primer clic. V110 incorpora la hoja
Resultados por Checklist al consolidado operativo y nombra cada PDF con su
reporte y fecha/periodo de corte. V111 ajusta Operación Diaria para mostrar
%Acondicionado y %Ubicado en tarjetas y sólo %Ubicado en la tabla. V112 repara
la API de ventas y V113 evita valores falsos. V114 inspecciona temporalmente el
layout real de Meta_ROPA_SEPTIEMBRE. V115 muestra Acondicionado y Ubicado en
piezas y porcentaje tanto en la tabla diaria como en su PDF. V116 hace que el
PDF Diario replique visualmente la pantalla. V117 unifica Día, Semanal y
Mensual: mismas tarjetas, mismo orden de detalle y misma identidad visual en PDF.
V118 consolida Día, Semanal y Mensual como filtro dentro de Centro Operativo.
"""
import web_app
from render_memory_patch import install as _install_render_memory_patch
from september_date_patch import install as _install_september_date_patch
from operations_diagnostic_patch import install as _install_operations_diagnostic_patch
from desktop_ui_patch import install as _install_desktop_ui_patch
from v87_operations_patch import install as _install_v87_operations_patch
from v90_render_parity_patch import install as _install_v90_render_parity_patch
from v93_daily_pdf_compact_patch import install as _install_v93_daily_pdf_compact_patch
from v94_zero_red_table_patch import install as _install_v94_zero_red_table_patch
from v95_web_zero_red_fix import install as _install_v95_web_zero_red_fix
from v96_center_exec_pdf_patch import install as _install_v96_center_exec_pdf_patch
from v102_final_filter_switch_patch import install as _install_v102_final_filter_switch_patch
from v103_compact_filter_bar_patch import install as _install_v103_compact_filter_bar_patch
from v104_single_filter_patch import install as _install_v104_single_filter_patch
from v105_week_month_pdf_mirror_patch import install as _install_v105_week_month_pdf_mirror_patch
from v106_pdf_selftest_patch import install as _install_v106_pdf_selftest_patch
from v107_portrait_recovery_chart_patch import install as _install_v107_portrait_recovery_chart_patch
from v108_project_mark_pdf_patch import install as _install_v108_project_mark_pdf_patch
from v109_macro_sales_patch import install as _install_v109_macro_sales_patch
from v109_sales_repair_startup import install as _install_v109_sales_repair_startup
from v110_operational_checklist_patch import install as _install_v110_operational_checklist_patch
from v111_daily_percent_fix import install as _install_v111_daily_percent_fix
from v112_sales_pdf_repair import install as _install_v112_sales_pdf_repair
from v113_sales_guard_patch import install as _install_v113_sales_guard_patch
from v114_sales_layout_probe import install as _install_v114_sales_layout_probe
from v115_daily_pieces_percent_patch import install as _install_v115_daily_pieces_percent_patch
from v116_reportlab_color_fix import install as _install_v116_reportlab_color_fix
from v116_daily_pdf_mirror_patch import install as _install_v116_daily_pdf_mirror_patch
from v117_operational_visual_parity_patch import install as _install_v117_operational_visual_parity_patch
from v118_centro_operativo_period_filter_patch import install as _install_v118_centro_operativo_period_filter_patch

_install_render_memory_patch(web_app)
_install_september_date_patch(web_app)
_install_operations_diagnostic_patch(web_app)
_install_desktop_ui_patch(web_app)
_install_v87_operations_patch(web_app)
_install_v90_render_parity_patch(web_app)
_install_v93_daily_pdf_compact_patch(web_app)
_install_v94_zero_red_table_patch(web_app)
_install_v95_web_zero_red_fix(web_app)
_install_v96_center_exec_pdf_patch(web_app)
_install_v102_final_filter_switch_patch(web_app)
_install_v103_compact_filter_bar_patch(web_app)
_install_v104_single_filter_patch(web_app)
_install_v105_week_month_pdf_mirror_patch(web_app)
_install_v106_pdf_selftest_patch(web_app)
_install_v107_portrait_recovery_chart_patch(web_app)
_install_v108_project_mark_pdf_patch(web_app)
_install_v109_macro_sales_patch(web_app)
_install_v109_sales_repair_startup(web_app)
_install_v110_operational_checklist_patch(web_app)
_install_v111_daily_percent_fix(web_app)
_install_v112_sales_pdf_repair(web_app)
_install_v113_sales_guard_patch(web_app)
_install_v114_sales_layout_probe(web_app)
_install_v115_daily_pieces_percent_patch(web_app)
_install_v116_reportlab_color_fix(web_app)
_install_v116_daily_pdf_mirror_patch(web_app)
_install_v117_operational_visual_parity_patch(web_app)
# V118 al final: reorganiza navegación sin alterar cálculos de V117.
_install_v118_centro_operativo_period_filter_patch(web_app)
app = web_app.app
