"""Entrada de producción para Render.

V157 mantiene intactos reportes, tablas, gráficas, PDF y Excel; retira las
capas V102/V103/V104 de filtros que generaban banners/duplicados y deja un
solo sistema de filtros nativo, con el diseño visual Opción 1 de los bocetos.
"""
import web_app
from fastapi import Request as _FastAPIRequest
import v121_operation_indicator_patch as _v121_operation_module
from render_memory_patch import install as _install_render_memory_patch
from september_date_patch import install as _install_september_date_patch
from operations_diagnostic_patch import install as _install_operations_diagnostic_patch
from desktop_ui_patch import install as _install_desktop_ui_patch
from v87_operations_patch import install as _install_v87_operations_patch
from v90_render_parity_patch import install as _install_v90_render_parity_patch
from v93_daily_pdf_compact_patch import install as _install_v93_daily_pdf_compact_patch
from v94_zero_red_table_patch import install as _install_v94_zero_red_table_patch
from v95_web_zero_red_fix import install as _install_v95_web_zero_red_fix
from v96_center_exec_pdf_patch import install as _install_v96_center_exec_pdf_patch
from v105_week_month_pdf_mirror_patch import install as _install_v105_week_month_pdf_mirror_patch
from v106_pdf_selftest_patch import install as _install_v106_pdf_selftest_patch
from v107_portrait_recovery_chart_patch import install as _install_v107_portrait_recovery_chart_patch
from v108_project_mark_pdf_patch import install as _install_v108_project_mark_pdf_patch
from v109_macro_sales_patch import install as _install_v109_macro_sales_patch
from v109_sales_repair_startup import install as _install_v109_sales_repair_startup
from v110_operational_checklist_patch import install as _install_v110_operational_checklist_patch
from v111_daily_percent_fix import install as _install_v111_daily_percent_fix
from v112_sales_pdf_repair import install as _install_v112_sales_pdf_repair
from v113_sales_guard_patch import install as _install_v113_sales_guard_patch
from v114_sales_layout_probe import install as _install_v114_sales_layout_probe
from v115_daily_pieces_percent_patch import install as _install_v115_daily_pieces_percent_patch
from v116_reportlab_color_fix import install as _install_v116_reportlab_color_fix
from v116_daily_pdf_mirror_patch import install as _install_v116_daily_pdf_mirror_patch
from v117_operational_visual_parity_patch import install as _install_v117_operational_visual_parity_patch
from v119_centro_operativo_safe_annual_patch import install as _install_v119_centro_operativo_safe_annual_patch
from v120_centro_operativo_preserve_reports_patch import install as _install_v120_centro_operativo_preserve_reports_patch
from v121_operation_indicator_patch import install as _install_v121_operation_indicator_patch
from v122_collaborator_entry_patch import install as _install_v122_collaborator_entry_patch
from v123_operation_visibility_patch import install as _install_v123_operation_visibility_patch
from v124_operation_main_module_patch import install as _install_v124_operation_main_module_patch
from v125_operation_tabs_patch import install as _install_v125_operation_tabs_patch
from v126_operation_summary_patch import install as _install_v126_operation_summary_patch
from v127_operation_demo_dashboard_patch import install as _install_v127_operation_demo_dashboard_patch
from v128_operation_demo_exact_patch import install as _install_v128_operation_demo_exact_patch
from v149_operation_summary_restore_patch import install as _install_v149_operation_summary_restore_patch
from v150_operations_endpoint_guard_patch import install as _install_v150_operations_endpoint_guard_patch
from v151_project_cards_scope_patch import install as _install_v151_project_cards_scope_patch
from v152_pdf_project_highlight_portrait_chart_patch import install as _install_v152_pdf_project_highlight_portrait_chart_patch
from v153_project_scope_backend_authoritative_patch import install as _install_v153_project_scope_backend_authoritative_patch
from v154_pdf_period_rules_patch import install_pre as _install_v154_pdf_period_pre, install_post as _install_v154_pdf_period_post
from v157_option1_boceto_filters_patch import install as _install_v157_option1_boceto_filters_patch

_v121_operation_module.Request = _FastAPIRequest

_install_render_memory_patch(web_app)
_install_september_date_patch(web_app)
_install_operations_diagnostic_patch(web_app)
_install_desktop_ui_patch(web_app)
_install_v87_operations_patch(web_app)
_install_v90_render_parity_patch(web_app)
_install_v93_daily_pdf_compact_patch(web_app)
_install_v94_zero_red_table_patch(web_app)
_install_v95_web_zero_red_fix(web_app)
_install_v96_center_exec_pdf_patch(web_app)
_install_v105_week_month_pdf_mirror_patch(web_app)
_install_v106_pdf_selftest_patch(web_app)
_install_v107_portrait_recovery_chart_patch(web_app)
_install_v108_project_mark_pdf_patch(web_app)
_install_v109_macro_sales_patch(web_app)
_install_v109_sales_repair_startup(web_app)
_install_v110_operational_checklist_patch(web_app)
_install_v111_daily_percent_fix(web_app)
_install_v112_sales_pdf_repair(web_app)
_install_v113_sales_guard_patch(web_app)
_install_v114_sales_layout_probe(web_app)
_install_v115_daily_pieces_percent_patch(web_app)
_install_v116_reportlab_color_fix(web_app)
_install_v116_daily_pdf_mirror_patch(web_app)
_install_v117_operational_visual_parity_patch(web_app)
_install_v119_centro_operativo_safe_annual_patch(web_app)
_install_v120_centro_operativo_preserve_reports_patch(web_app)
_install_v121_operation_indicator_patch(web_app)
_install_v122_collaborator_entry_patch(web_app)
_install_v123_operation_visibility_patch(web_app)
_install_v124_operation_main_module_patch(web_app)
_install_v125_operation_tabs_patch(web_app)
_install_v126_operation_summary_patch(web_app)
_install_v127_operation_demo_dashboard_patch(web_app)
_install_v128_operation_demo_exact_patch(web_app)

# Operación real preservada.
_install_v149_operation_summary_restore_patch(web_app)
_install_v150_operations_endpoint_guard_patch(web_app)
_install_v151_project_cards_scope_patch(web_app)

# Exportaciones y alcance Proyecto preservados.
_install_v154_pdf_period_pre(web_app)
_install_v152_pdf_project_highlight_portrait_chart_patch(web_app)
_install_v153_project_scope_backend_authoritative_patch(web_app)
_install_v154_pdf_period_post(web_app)

# V157: filtro único nativo + diseño Opción 1 de bocetos. Sin V102/V103/V104/V156.
_install_v157_option1_boceto_filters_patch(web_app)
app = web_app.app
