"""V128 · Demo visual de Operación fiel a los bocetos aprobados.

Sólo afecta la presentación temporal del Super Administrador dentro del módulo
Operación. No llama endpoints de escritura ni modifica tablas reales. Quitar la
instalación de este parche devuelve la interfaz a V127/V126 sin perder datos.
"""
from __future__ import annotations

from fastapi.responses import HTMLResponse


def install(m):
    if getattr(m, "_V128_OPERATION_DEMO_EXACT", False):
        return

    css = r'''<style id="v128-operation-demo-css">
body.v128-demo-operation #globalFilters,
body.v128-demo-operation #operativoNav,
body.v128-demo-operation #operativoPeriodBar,
body.v128-demo-operation #operativoDynamicTitle,
body.v128-demo-operation #operativoDynamicSub{display:none!important}
body.v128-demo-operation .hero{background:linear-gradient(115deg,#123f78 0%,#0b4b94 55%,#1764b8 100%);border-radius:16px;box-shadow:none}
body.v128-demo-operation .hero h1{display:flex;align-items:center;gap:9px}
.v128-badge{display:inline-flex;align-items:center;justify-content:center;padding:4px 10px;border-radius:999px;background:#a7efff;color:#075c83;font-size:10px;font-weight:950;letter-spacing:.03em}
.v128-wrap{display:block;width:100%;max-width:100%;padding-bottom:8px;color:#123a72}
.v128-filterbox{background:#fff;border:1px solid #d9e3ef;border-radius:15px;padding:12px;margin:0 0 9px;box-shadow:0 1px 2px rgba(15,52,99,.03)}
.v128-filtergrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px}.v128-field label{display:block;color:#5d6e86;font-size:8px;font-weight:950;text-transform:uppercase;margin:0 0 5px}.v128-field select,.v128-field input{width:100%;min-width:0;height:46px;border:1px solid #cbd8e8;border-radius:10px;background:#fff;color:#123a72;padding:8px 11px;font-size:15px;outline:none}.v128-consult{grid-column:1/-1;width:100%;height:48px;border:0;border-radius:11px;background:linear-gradient(90deg,#2370e8,#1677f3);color:#fff;font-size:17px;font-weight:950;cursor:pointer}
.v128-tabs{display:grid;grid-template-columns:.82fr 1.02fr 1.45fr 1.03fr .90fr;gap:5px;margin:8px 0 10px}.v128-tab{min-width:0;border:1px solid #d4dfec;background:#fff;color:#5c6d85;border-radius:999px;padding:9px 5px;font-size:9px;font-weight:900;white-space:nowrap;overflow:hidden;text-overflow:clip;cursor:pointer}.v128-tab.active{background:linear-gradient(90deg,#246fe5,#1678f4);border-color:#246fe5;color:#fff}
.v128-panel{background:#fff;border:1px solid #d9e3ef;border-radius:14px;padding:13px;margin:9px 0}.v128-panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:8px}.v128-panel h2,.v128-panel h3,.v128-card h3{margin:0;color:#0f3975;font-weight:950}.v128-panel h2{font-size:18px}.v128-panel h3,.v128-card h3{font-size:14px}.v128-sub{font-size:9px;color:#6d7c92;margin-top:3px;line-height:1.45}.v128-status{display:inline-flex;padding:6px 10px;border-radius:999px;background:#dcf9e7;color:#197d45;font-size:8px;font-weight:950;white-space:nowrap}
.v128-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:11px}.v128-kpi{min-width:0;border:1px solid #dce6f1;border-radius:12px;padding:9px 8px;background:#fff}.v128-kpi.green{background:#eefbf4;border-color:#c7ead6}.v128-kpi.purple{background:#f6f2ff;border-color:#ded1ff}.v128-kpi.red{background:#fff4f4;border-color:#ffd1d1}.v128-kpi .top{display:flex;align-items:center;gap:5px;min-width:0}.v128-kpi .ico{font-size:16px;line-height:1;flex:0 0 auto}.v128-kpi small{display:block;color:#53657e;font-size:7px;font-weight:900;line-height:1.2}.v128-kpi b{display:block;color:#103f82;font-size:19px;margin-top:5px;line-height:1}.v128-kpi.green b,.v128-kpi.green small{color:#168448}.v128-kpi.purple b,.v128-kpi.purple small{color:#6035cf}.v128-kpi.red b,.v128-kpi.red small{color:#d93443}.v128-kpi em{display:block;font-style:normal;color:#77869b;font-size:7px;margin-top:5px;line-height:1.2}
.v128-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.v128-card{min-width:0;background:#fff;border:1px solid #d9e3ef;border-radius:14px;padding:12px}.v128-card .v128-sub{margin-bottom:7px}.v128-table{width:100%;border-collapse:separate;border-spacing:0;table-layout:fixed;font-size:8px;color:#123a72}.v128-table th{background:#f0f5fb;color:#52647d;text-align:left;font-weight:900;padding:7px 5px;border-bottom:1px solid #d8e3ef}.v128-table td{padding:7px 5px;border-bottom:1px solid #e6edf5;vertical-align:middle;overflow:hidden;text-overflow:ellipsis}.v128-table tr:last-child td{border-bottom:0}.v128-table .total td{background:#edf6ff;color:#0b67cd;font-weight:950}.v128-table .num{text-align:right}.v128-table .center{text-align:center}
.v128-store{display:grid;grid-template-columns:74px minmax(50px,1fr) 50px;gap:6px;align-items:center;margin:8px 0;font-size:8px}.v128-store b{overflow:hidden;text-overflow:ellipsis}.v128-track{height:12px;background:#e9eef4;border-radius:999px;overflow:hidden}.v128-fill{height:100%;background:linear-gradient(90deg,#2a70df,#2377ef);border-radius:999px}.v128-pill{background:#eaf9ef;color:#168044;border-radius:999px;padding:4px 5px;text-align:center;font-weight:950;font-size:7px}
.v128-alert{display:grid;grid-template-columns:24px minmax(0,1fr) 12px;gap:7px;align-items:center;padding:8px 0;border-bottom:1px solid #e8eef5}.v128-alert:last-child{border-bottom:0}.v128-alert .dot{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;color:#fff;background:#2275e9;font-weight:950}.v128-alert .dot.red{background:#ee4050}.v128-alert .dot.orange{background:#f5a000}.v128-alert b{display:block;font-size:8px;color:#153c73;line-height:1.25}.v128-alert span{display:block;font-size:7px;color:#748298;margin-top:2px;line-height:1.25}.v128-alert .chev{font-size:13px;color:#748298}
.v128-inputgrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:12px}.v128-inputbox{display:grid;grid-template-columns:40px minmax(0,1fr);gap:8px;align-items:center;border:1px solid #dce6f0;border-radius:12px;padding:10px}.v128-inputbox .icon{font-size:23px;text-align:center}.v128-inputbox label{display:block;font-size:9px;color:#5f7088;margin-bottom:5px}.v128-inputbox input{width:100%;height:42px;border:1px solid #cbd8e8;border-radius:9px;padding:7px 9px;color:#103c77;font-size:18px;font-weight:900;background:#fff}.v128-primary,.v128-secondary{width:100%;min-height:48px;border-radius:11px;font-size:15px;font-weight:950;cursor:pointer;margin-top:9px}.v128-primary{border:0;background:linear-gradient(90deg,#246fe5,#1478f4);color:#fff}.v128-secondary{border:1.5px solid #1e73ea;background:#fff;color:#176de1}.v128-toast{display:none;margin-top:8px;padding:8px;border-radius:9px;background:#eef7ff;color:#155cae;font-size:9px;font-weight:800}.v128-toast.show{display:block}
.v128-quick{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin-top:10px}.v128-quick .v128-kpi{padding:9px 6px}.v128-history{margin-top:10px}.v128-form{display:grid;grid-template-columns:155px minmax(0,1fr);gap:8px 12px;align-items:center;margin-top:12px}.v128-form label{font-size:10px;color:#153c73}.v128-form select,.v128-form input{width:100%;height:44px;border:1px solid #cbd8e8;border-radius:9px;padding:8px 10px;color:#103c77;font-size:14px;background:#fff}.v128-total{display:flex;align-items:center;gap:10px;background:#eaf4ff;border-radius:10px;padding:11px;margin-top:10px;color:#123e79}.v128-total .bars{font-size:25px}.v128-total b{display:block;font-size:12px}.v128-total span{display:block;font-size:9px;margin-top:2px}
.v128-prod-kpis{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin-top:10px}.v128-prod-kpi{display:grid;grid-template-columns:42px minmax(0,1fr);align-items:center;gap:8px;border:1px solid #dbe6f2;border-radius:11px;padding:10px;background:#f6f9ff}.v128-prod-kpi.green{background:#eefbf4;border-color:#c8ecd8}.v128-prod-kpi.purple{background:#f7f3ff;border-color:#e0d4ff}.v128-prod-kpi .ico{font-size:24px;text-align:center}.v128-prod-kpi small{display:block;font-size:9px;color:#53657e}.v128-prod-kpi b{display:block;font-size:21px;color:#103f82;margin-top:2px}.v128-prod-kpi.green b{color:#14834a}.v128-prod-kpi.purple b{color:#6637d4}
.v128-rankrow{display:grid;grid-template-columns:24px 112px minmax(70px,1fr) 54px;gap:6px;align-items:center;padding:6px 0;font-size:8px;border-bottom:1px solid #edf1f6}.v128-rankrow:last-child{border-bottom:0}.v128-rankrow .bar{height:13px;background:#e7edf4;border-radius:999px;overflow:hidden}.v128-rankrow .bar i{display:block;height:100%;background:linear-gradient(90deg,#2d72e3,#1976ef);border-radius:999px}.v128-rankrow .val{text-align:right;font-weight:900}
.v128-stdgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:12px}.v128-std{border:1px solid #dce6f1;border-radius:12px;padding:11px;background:#f8fbff}.v128-std .head{display:flex;gap:8px;align-items:center;font-size:10px;font-weight:900;color:#123d77}.v128-std .ico{font-size:22px}.v128-std input{width:100%;height:44px;margin-top:8px;border:1px solid #cbd8e8;border-radius:9px;padding:7px 8px;font-size:18px;font-weight:900;color:#103f82}.v128-std small{display:block;color:#718096;font-size:8px;margin-top:4px}.v128-standard-read{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.v128-standard-read .v128-prod-kpi{grid-template-columns:32px 1fr}.v128-standard-read .red{background:#fff4f4;border-color:#ffd1d1}.v128-standard-read .red b{color:#e12d3d}
.v128-demo-note{display:flex;align-items:center;gap:7px;margin:7px 0 9px;padding:8px 10px;border:1px solid #b8d8ff;border-radius:10px;background:#eef6ff;color:#174d87;font-size:8px;font-weight:850}.v128-demo-note b{font-weight:950}
.v128-delete{border:0;background:transparent;color:#ef3340;font-size:17px;cursor:pointer}.v128-green{color:#168448!important}.v128-red{color:#db3342!important}
@media(max-width:900px){
 body.v128-demo-operation .main{padding-left:5px;padding-right:5px}
 .v128-filterbox{padding:10px}.v128-filtergrid{gap:6px}.v128-field select,.v128-field input{height:42px;font-size:12px;padding:6px}.v128-consult{height:46px;font-size:15px}
 .v128-tabs{gap:4px}.v128-tab{padding:8px 2px;font-size:clamp(7px,2.1vw,9px)}
 .v128-panel,.v128-card{padding:10px}.v128-panel h2{font-size:15px}.v128-panel h3,.v128-card h3{font-size:12px}.v128-sub{font-size:8px}
 .v128-kpis{gap:5px}.v128-kpi{padding:8px 5px}.v128-kpi .ico{font-size:13px}.v128-kpi small{font-size:6.5px}.v128-kpi b{font-size:15px}.v128-kpi em{font-size:6px}
 .v128-grid2{gap:6px}.v128-card{padding:9px}.v128-table{font-size:6.6px}.v128-table th,.v128-table td{padding:5px 3px}.v128-store{grid-template-columns:58px 1fr 42px;gap:4px;font-size:6.8px;margin:6px 0}.v128-pill{font-size:6px;padding:3px}.v128-alert{grid-template-columns:20px 1fr 9px;gap:5px;padding:6px 0}.v128-alert .dot{width:19px;height:19px;font-size:8px}.v128-alert b{font-size:6.8px}.v128-alert span{font-size:6px}
 .v128-inputgrid{gap:6px}.v128-inputbox{grid-template-columns:30px 1fr;gap:5px;padding:8px}.v128-inputbox .icon{font-size:18px}.v128-inputbox label{font-size:7px}.v128-inputbox input{height:38px;font-size:15px}.v128-primary,.v128-secondary{min-height:44px;font-size:13px}
 .v128-quick{gap:5px}.v128-form{grid-template-columns:78px minmax(0,1fr);gap:7px 8px}.v128-form label{font-size:8px}.v128-form select,.v128-form input{height:42px;font-size:12px}.v128-prod-kpis{gap:6px}.v128-prod-kpi{grid-template-columns:30px 1fr;padding:8px;gap:5px}.v128-prod-kpi .ico{font-size:18px}.v128-prod-kpi small{font-size:7px}.v128-prod-kpi b{font-size:17px}
 .v128-rankrow{grid-template-columns:18px 72px minmax(45px,1fr) 42px;gap:4px;font-size:6.8px}.v128-stdgrid{gap:5px}.v128-std{padding:8px}.v128-std .head{font-size:7px;gap:4px}.v128-std .ico{font-size:16px}.v128-std input{height:38px;font-size:15px}.v128-std small{font-size:6.5px}.v128-standard-read{gap:5px}.v128-standard-read .v128-prod-kpi{grid-template-columns:22px 1fr}
}
@media(max-width:370px){.v128-tab{font-size:6.5px}.v128-filtergrid{grid-template-columns:repeat(3,minmax(0,1fr))}.v128-kpis,.v128-quick{grid-template-columns:repeat(4,minmax(0,1fr))}.v128-grid2{grid-template-columns:repeat(2,minmax(0,1fr))}.v128-stdgrid,.v128-standard-read{grid-template-columns:repeat(3,minmax(0,1fr))}}
</style>'''

    js = r'''<script id="v128-operation-demo-js">
(function(){
 const OP='Operación',isSuper=()=>USER?.role==='superadmin',fmt=n=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:0}),pct=n=>`${Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:1})}%`;
 window.V128_TAB=window.V128_TAB||'summary';
 const TABS=[['summary','Resumen'],['daily','Captura diaria'],['capture','Cargar productividad'],['productivity','Productividad'],['standards','Estándares']];
 function safe(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
 function activate(){document.body.classList.add('v128-demo-operation');const c=$('#operativoCentro'),d=$('#operativoDynamic');c?.classList.add('hidden');d?.classList.remove('hidden');const h=$('#heroTitle');if(h)h.innerHTML='Operación <span class="v128-badge">DEMO</span>';const s=$('#heroSub');if(s)s.textContent='Control diario, productividad por colaborador y eficiencia de mercancía';document.querySelectorAll('[data-main]').forEach(x=>x.classList.toggle('active',x.dataset.main==='operation'))}
 function tabs(){return `<div class="v128-tabs">${TABS.map(([k,l])=>`<button class="v128-tab ${V128_TAB===k?'active':''}" data-v128-tab="${k}">${l}</button>`).join('')}</div>`}
 function filters(type,period,store){return `<div class="v128-filterbox"><div class="v128-filtergrid"><div class="v128-field"><label>Vista</label><select id="v128View"><option>${type}</option></select></div><div class="v128-field"><label>Periodo</label><select id="v128Period"><option>${period}</option></select></div><div class="v128-field"><label>Tienda</label><select id="v128Store"><option>${store}</option></select></div><button class="v128-consult v128-demo-action">Consultar</button></div></div>`}
 function note(){return `<div class="v128-demo-note"><b>DEMO</b><span>Datos ficticios para visualizar el indicador lleno. No modifica la información real.</span></div>`}
 function icon(x){return `<span class="ico">${x}</span>`}
 function summary(){const k=[['🚚','Llegada Origen','148,320','Colgado + Doblado',''],['▥','Productividad registrada','139,870','Acumulado','green'],['◆','Mercancía liberada','136,540','Origen','purple'],['▲','Pendiente','8,450','Por liberar','red'],['%','Eficiencia','94.3%','Procesadas / carga',''],['👥','Prod. promedio','1,042','Pzas / colaborador / día',''],['◎','Cumplimiento','101.8%','Vs estándar','green'],['👥','Colaboradores','128','Con productividad','']];const origin=[['Origen','148,320','92.6%'],['Cambios','7,180','4.5%'],['Muertos','4,680','2.9%'],['Total','160,180','100.0%']];const stores=[['Iztapalapa',97.2],['Vallejo',95.6],['Ecatepec',93.1],['Puebla',92.8],['León',90.4]];const top=[['Ana Martínez','2,436'],['Carlos López','2,215'],['María González','2,102'],['Jorge Ramírez','1,998'],['Laura Torres','1,876']];const alerts=[['red','!','2 tiendas con eficiencia menor a 90%','Puebla (88.5%), León (86.2%)'],['orange','!','Pendiente de liberar > 5,000','8,450 prendas en total'],['','i','3 tiendas sin captura en los últimos 3 días','Toluca, Cuernavaca, Querétaro'],['','i','Productividad por debajo del estándar','12 colaboradores']];return `${filters('Año','2026','Compañía')}${tabs()}${note()}<div class="v128-panel"><h2>Resumen ejecutivo · Ene – Sep 2026</h2><div class="v128-sub">Indicadores acumulados del año al 11 de septiembre</div><div class="v128-kpis">${k.map(x=>`<div class="v128-kpi ${x[4]}"><div class="top">${icon(x[0])}<small>${x[1]}</small></div><b>${x[2]}</b><em>${x[3]}</em></div>`).join('')}</div></div><div class="v128-grid2"><div class="v128-card"><h3>Origen vs Cambios y Muertos</h3><div class="v128-sub">Acumulado 2026</div><table class="v128-table"><thead><tr><th>Tipo</th><th class="num">Cantidad</th><th class="num">% del total</th></tr></thead><tbody>${origin.map((r,i)=>`<tr class="${i===3?'total':''}"><td>${r[0]}</td><td class="num">${r[1]}</td><td class="num">${r[2]}</td></tr>`).join('')}</tbody></table></div><div class="v128-card"><h3>Desempeño por tienda</h3><div class="v128-sub">Llegada vs mercancía liberada · % Eficiencia</div>${stores.map(r=>`<div class="v128-store"><b>${r[0]}</b><div class="v128-track"><div class="v128-fill" style="width:${r[1]}%"></div></div><span class="v128-pill">${r[1]}%</span></div>`).join('')}</div><div class="v128-card"><h3>Top 5 colaboradores</h3><div class="v128-sub">Por productividad registrada · acumulado</div><table class="v128-table"><thead><tr><th style="width:24px">#</th><th>Colaborador</th><th class="num">Productividad</th></tr></thead><tbody>${top.map((r,i)=>`<tr><td>${i+1}</td><td>${r[0]}</td><td class="num">${r[1]}</td></tr>`).join('')}</tbody></table></div><div class="v128-card"><h3>Alertas operativas <span style="float:right;font-size:8px;color:#1773e7">Ver todas</span></h3>${alerts.map(a=>`<div class="v128-alert"><span class="dot ${a[0]}">${a[1]}</span><div><b>${a[2]}</b><span>${a[3]}</span></div><span class="chev">›</span></div>`).join('')}</div></div>`}
 function daily(){const q=[['▲','Pendiente inicial','185','red'],['👥','Procesadas','1,244',''],['◎','Liberadas','1,215','green'],['%','Eficiencia','95.1%','']];return `${filters('Día','2026-09-11','Olivar')}${tabs()}${note()}<div class="v128-panel"><div class="v128-panel-head"><div><h2>Captura diaria · Origen</h2><div class="v128-sub">Origen agrupa <b>Colgado + Doblado</b>. Sólo captura el total de llegada y mercancía liberada.</div></div><span class="v128-status">En captura</span></div><div class="v128-inputgrid"><div class="v128-inputbox"><div class="icon">🚚</div><div><label>Origen · Llegada</label><input value="1280" inputmode="numeric"></div></div><div class="v128-inputbox"><div class="icon">◆</div><div><label>Origen · Mercancía liberada</label><input value="1215" inputmode="numeric"></div></div></div><button class="v128-primary v128-demo-action">Guardar captura</button><button class="v128-secondary v128-demo-action">Cerrar día</button><div class="v128-toast"></div></div><div class="v128-panel"><h2>Lectura rápida del día</h2><div class="v128-quick">${q.map(x=>`<div class="v128-kpi ${x[3]}"><div class="top">${icon(x[0])}<small>${x[1]}</small></div><b>${x[2]}</b></div>`).join('')}</div></div><div class="v128-panel"><h2>Historial de captura del día</h2><div class="v128-history"><table class="v128-table"><thead><tr><th>Hora</th><th>Tipo</th><th class="num">Origen · Llegada</th><th class="num">Origen · Liberada</th></tr></thead><tbody><tr><td>08:10</td><td>Captura inicial</td><td class="num">1,180</td><td class="num">1,120</td></tr><tr><td>12:35</td><td>Ajuste</td><td class="num">1,240</td><td class="num">1,188</td></tr><tr><td>17:42</td><td>Última captura</td><td class="num">1,280</td><td class="num">1,215</td></tr></tbody></table></div></div>`}
 function capture(){return `${filters('Día','2026-09-11','Olivar')}${tabs()}${note()}<div class="v128-panel"><h2>Cargar productividad</h2><div class="v128-sub">Cada colaborador registra sus piezas. Tienda, nombre y nómina se relacionan automáticamente con su usuario.</div><div class="v128-form"><label>Fecha</label><input type="date" value="2026-09-11"><label>Colaborador</label><select><option>Jesús Del Ángel · 10284</option></select><label>Origen</label><select><option>Doblado</option><option>Colgado</option></select><label>Actividad</label><select><option>Acondicionado</option><option>Ubicado</option><option>Clasificado</option></select><label>Piezas</label><input value="842" inputmode="numeric"></div><button class="v128-primary v128-demo-action">Guardar productividad</button><div class="v128-toast"></div></div><div class="v128-panel"><h2>Mis capturas del día</h2><div class="v128-sub">Tus registros de productividad del día seleccionado.</div><table class="v128-table" style="margin-top:9px"><thead><tr><th style="width:25px">#</th><th>Origen</th><th>Actividad</th><th class="num">Piezas</th><th class="center" style="width:42px">Acción</th></tr></thead><tbody><tr><td>1</td><td>Doblado</td><td>Acondicionado</td><td class="num">842</td><td class="center"><button class="v128-delete v128-demo-action">⌫</button></td></tr><tr><td>2</td><td>Colgado</td><td>Ubicado</td><td class="num">265</td><td class="center"><button class="v128-delete v128-demo-action">⌫</button></td></tr><tr><td>3</td><td>Doblado</td><td>Clasificado</td><td class="num">118</td><td class="center"><button class="v128-delete v128-demo-action">⌫</button></td></tr></tbody></table><div class="v128-total"><span class="bars">▥</span><div><b>Total del día</b><span>1,225 piezas · 3 registros</span></div></div></div>`}
 function productivity(){const ranks=[['Ana Martínez',1248],['Carlos López',1172],['María González',1086],['Jorge Ramírez',1015],['Laura Torres',982]],mx=1248;return `${filters('Semanal','2026-W37','Compañía')}${tabs()}${note()}<div class="v128-panel"><h2>Productividad por colaborador</h2><div class="v128-sub">Resultado semanal acumulado</div><div class="v128-prod-kpis"><div class="v128-prod-kpi"><div class="ico">◆</div><div><small>Piezas registradas</small><b>24,860</b></div></div><div class="v128-prod-kpi green"><div class="ico">👥</div><div><small>Colaboradores</small><b>34</b></div></div><div class="v128-prod-kpi purple"><div class="ico">▥</div><div><small>Prod. promedio</small><b>731</b></div></div><div class="v128-prod-kpi green"><div class="ico">◎</div><div><small>Cumplimiento</small><b>98.4%</b></div></div></div></div><div class="v128-panel"><h2>Ranking de colaboradores</h2><div class="v128-sub">Piezas registradas · acumulado semanal</div>${ranks.map((r,i)=>`<div class="v128-rankrow"><b>${i+1}</b><span>${r[0]}</span><div class="bar"><i style="width:${r[1]/mx*100}%"></i></div><span class="val">${fmt(r[1])}</span></div>`).join('')}</div><div class="v128-panel"><h2>Detalle por origen</h2><div class="v128-sub">Piezas registradas · acumulado semanal</div><table class="v128-table" style="margin-top:8px"><thead><tr><th>Origen</th><th class="num">Piezas</th><th class="num">% del total</th></tr></thead><tbody><tr><td>Colgado</td><td class="num">13,420</td><td class="num">54.0%</td></tr><tr><td>Doblado</td><td class="num">9,860</td><td class="num">39.7%</td></tr><tr><td>Cambios y Muertos</td><td class="num">1,580</td><td class="num">6.3%</td></tr></tbody></table></div><div class="v128-panel"><h2>Detalle del periodo</h2><div class="v128-sub">Últimos registros del periodo</div><table class="v128-table" style="margin-top:8px"><thead><tr><th>Colaborador</th><th>Tienda</th><th>Origen</th><th class="num">Piezas</th><th class="num">% cumplimiento</th></tr></thead><tbody><tr><td>Ana Martínez</td><td>Vallejo</td><td>Colgado</td><td class="num">1,248</td><td class="num">102.3%</td></tr><tr><td>Carlos López</td><td>Iztapalapa</td><td>Doblado</td><td class="num">1,172</td><td class="num">97.8%</td></tr><tr><td>María González</td><td>Ecatepec</td><td>Cambios</td><td class="num">1,086</td><td class="num">95.1%</td></tr></tbody></table></div>`}
 function standards(){return `${filters('Año','2026','Compañía')}${tabs()}${note()}<div class="v128-panel"><h2>Estándares de productividad</h2><div class="v128-sub">Valores de referencia por jornada usados para el cumplimiento del indicador.</div><div class="v128-stdgrid"><div class="v128-std"><div class="head"><span class="ico">⌁</span>Colgado</div><input value="1228"><small>pzas/jornada</small></div><div class="v128-std"><div class="head"><span class="ico">▤</span>Doblado</div><input value="906"><small>pzas/jornada</small></div><div class="v128-std"><div class="head"><span class="ico">↻</span>Cambios y Muertos</div><input value="670"><small>pzas/jornada</small></div></div><button class="v128-primary v128-demo-action">Guardar estándares</button><div class="v128-toast"></div></div><div class="v128-panel"><h2>Lectura del estándar</h2><div class="v128-standard-read" style="margin-top:10px"><div class="v128-prod-kpi"><div class="ico">▥</div><div><small>Estándar total</small><b>2,804</b></div></div><div class="v128-prod-kpi green"><div class="ico">👥</div><div><small>Promedio actual</small><b>2,761</b></div></div><div class="v128-prod-kpi red"><div class="ico">▲</div><div><small>Brecha</small><b>-43</b></div></div></div></div><div class="v128-panel"><h2>Historial de cambios</h2><table class="v128-table" style="margin-top:9px"><thead><tr><th>Fecha</th><th>Usuario</th><th>Campo</th><th class="num">Anterior</th><th class="num">Nuevo</th></tr></thead><tbody><tr><td>2026-08-15</td><td>Super Administrador</td><td>Colgado</td><td class="num">1,180</td><td class="num">1,228</td></tr><tr><td>2026-08-15</td><td>Super Administrador</td><td>Doblado</td><td class="num">880</td><td class="num">906</td></tr><tr><td>2026-08-15</td><td>Super Administrador</td><td>Cambios y Muertos</td><td class="num">650</td><td class="num">670</td></tr></tbody></table></div>`}
 function render(){if(!isSuper())return false;activate();const content=$('#operativoDynamicContent');if(!content)return false;const views={summary,daily,capture,productivity,standards};content.innerHTML=`<div class="v128-wrap">${(views[V128_TAB]||summary)()}</div>`;bind();return true}
 function bind(){document.querySelectorAll('[data-v128-tab]').forEach(b=>b.onclick=e=>{e.preventDefault();V128_TAB=b.dataset.v128Tab;V125_OPERATION_TAB=V128_TAB==='summary'?'summary':V128_TAB;render()});document.querySelectorAll('.v128-demo-action').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const panel=b.closest('.v128-panel')||b.closest('.v128-filterbox'),toast=panel?.querySelector('.v128-toast');if(toast){toast.textContent='DEMO · Acción simulada. No modifica datos reales.';toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2200)}else{const old=b.textContent;b.textContent='DEMO · Sin cambios reales';setTimeout(()=>b.textContent=old,1500)}})}
 function installWrapper(){const base=window.renderOperativoView;if(typeof base!=='function'||base.__v128Exact)return;const w=async function(name,force=false){if(name===OP&&isSuper()){render();return}return base(name,force)};w.__v128Exact=true;w.__v128Base=base;window.renderOperativoView=w}
 [0,250,900,1800,3200].forEach(ms=>setTimeout(installWrapper,ms));
 document.addEventListener('click',e=>{const main=e.target.closest?.('[data-main="operation"]');if(main&&isSuper()){V128_TAB='summary';setTimeout(render,120)}},true);
 setTimeout(()=>{if(isSuper()&&(window.MAIN==='operation'||window.OP_VIEW===OP)){V128_TAB='summary';render()}},500);
 console.info('[V128] Demo exacto de Operación activo; cinco pestañas visuales sin escritura de datos.');
})();
</script>'''

    @m.app.middleware("http")
    async def _v128_html(request, call_next):
        response = await call_next(request)
        if request.url.path != "/" or getattr(response, "status_code", 200) != 200:
            return response
        try:
            body = b""
            async for chunk in response.body_iterator:
                body += chunk
            html = body.decode("utf-8", errors="replace")
            if "v128-operation-demo-js" not in html:
                html = html.replace("</head>", css + "</head>", 1).replace("</body>", js + "</body>", 1)
            return HTMLResponse(html, status_code=response.status_code, headers={
                "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
                "Pragma": "no-cache", "Expires": "0", "X-Operations-UI-Version": "V128-DEMO-EXACT"
            })
        except Exception as exc:
            print(f"[V128] HTML warning: {type(exc).__name__}: {exc}", flush=True)
            return response

    m._V128_OPERATION_DEMO_EXACT = True
    print("[V128] Demo exacto de Operación instalado; Resumen, Captura, Carga, Productividad y Estándares sin tocar datos reales.", flush=True)
