"""V133 · Demo Comercial compacto e interactivo.

Sustituye visualmente V132 para el propietario con una maqueta densa equivalente
al boceto aprobado. Mantiene datos ficticios, hace funcionales filtros y pestañas
y muestra las reglas V131 de lentos, sugerido 0, tienda comparable y sin ubicación.
No escribe ni modifica datos reales.
"""
from __future__ import annotations

from fastapi.responses import HTMLResponse


def install(m):
    if getattr(m, "_V133_COMMERCIAL_DEMO_COMPACT", False):
        return

    css = r'''<style id="v133-commercial-demo-css">
#v133CommercialDemoHost{display:none;position:relative;z-index:2}
body.v133-commercial-demo #v133CommercialDemoHost{display:block!important}
body.v133-commercial-demo #v132CommercialDemoHost{display:none!important}
body.v133-commercial-demo #analysisNav,body.v133-commercial-demo #globalFilters,body.v133-commercial-demo #v103FilterShell,body.v133-commercial-demo #v103ClassicBack{display:none!important}
body.v133-commercial-demo main.main>section.page{display:none!important}
#v133CommercialDemoHost *{box-sizing:border-box}
.v133-shell{display:grid;gap:6px;margin:7px 0 12px;touch-action:manipulation}
.v133-badge{display:inline-flex;margin-left:5px;padding:2px 6px;border-radius:999px;background:#bff3ff;color:#075a7b;font-size:8px;font-weight:950;vertical-align:middle}
.v133-filters{background:#fff;border:1px solid #d8e2ed;border-radius:9px;padding:6px;display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}
.v133-field label{display:block;font-size:5.5px;font-weight:950;color:#6b7a91;text-transform:uppercase;letter-spacing:.2px;margin:0 0 2px}
.v133-field select{width:100%;height:26px;border:1px solid #cedae7;border-radius:5px;background:#fff;color:#173f78;padding:2px 5px;font-size:7px;font-weight:850;pointer-events:auto!important}
.v133-query{grid-column:1/-1;height:27px;border:0;border-radius:5px;background:#2570e8;color:#fff;font-size:7px;font-weight:950;cursor:pointer;pointer-events:auto!important}
.v133-tabs{display:flex;gap:4px;overflow-x:auto;white-space:nowrap;scrollbar-width:none;padding:1px 0}.v133-tabs::-webkit-scrollbar{display:none}
.v133-tab{flex:0 0 auto;border:1px solid #d4dfec;background:#fff;color:#53657e;border-radius:999px;padding:5px 8px;font-size:6px;font-weight:900;cursor:pointer;pointer-events:auto!important;min-height:24px}
.v133-tab.active{background:#2670e8;border-color:#2670e8;color:#fff}
.v133-note{padding:5px 7px;border:1px solid #b7d6ff;background:#eff6ff;border-radius:7px;color:#174b85;font-size:6px;font-weight:850}
.v133-content{display:grid;gap:6px;min-width:0}
.v133-panel{background:#fff;border:1px solid #dce5ef;border-radius:8px;padding:7px;min-width:0;overflow:hidden}
.v133-head{display:flex;justify-content:space-between;gap:5px;align-items:flex-start}.v133-title{font-size:9px;font-weight:950;color:#123b73;line-height:1.15}.v133-sub{font-size:5.5px;color:#718096;margin-top:2px}.v133-link{font-size:5px;color:#1769e8;font-weight:900;white-space:nowrap}
.v133-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px;margin-top:6px}.v133-kpi{border:1px solid #dfe7f0;border-radius:6px;padding:5px;background:#fff;display:grid;grid-template-columns:22px minmax(0,1fr);gap:4px;align-items:center;min-width:0;min-height:48px}.v133-icon{width:22px;height:22px;border-radius:50%;display:grid;place-items:center;background:#edf5ff;color:#1769e8;font-size:11px;font-weight:950}.v133-kpi small{display:block;font-size:5px;color:#64748b;font-weight:900;line-height:1.1}.v133-kpi b{display:block;font-size:9.5px;color:#103d7c;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v133-kpi em{display:block;font-size:4.5px;color:#8290a2;font-style:normal}.v133-good{background:#effbf4;border-color:#c8ead6}.v133-good b{color:#168447}.v133-purple{background:#f7f3ff;border-color:#ded2ff}.v133-purple b{color:#6030cb}.v133-warn{background:#fff9e9;border-color:#f6df9f}
.v133-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px}.v133-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:4px}.v133-section{border:1px solid #dfe7f0;border-radius:6px;padding:5px;min-width:0}.v133-section .top{display:flex;gap:4px;align-items:center}.v133-section .garment{font-size:13px}.v133-section h4{margin:0;font-size:6px;color:#173f78}.v133-section b{display:block;font-size:8px;color:#103d7c;margin-top:3px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v133-section small{display:block;font-size:4.5px;color:#718096;line-height:1.25;margin-top:1px}
.v133-bars{display:grid;gap:3px;margin-top:5px}.v133-bar{display:grid;grid-template-columns:45px minmax(40px,1fr) 35px;gap:3px;align-items:center;font-size:5px;color:#173f78}.v133-bar b{overflow:hidden;text-overflow:ellipsis}.v133-track{height:8px;border-radius:3px;background:#e7edf4;overflow:hidden}.v133-fill{height:100%;border-radius:3px;background:#2875ed}.v133-bar.current{font-weight:950}.v133-bar.current .v133-fill{background:#0f4fae}
.v133-tablewrap{overflow:auto;margin-top:5px;border:1px solid #e3eaf2;border-radius:5px;-webkit-overflow-scrolling:touch}.v133-table{width:100%;border-collapse:collapse;font-size:5px;min-width:330px}.v133-table.wide{min-width:820px}.v133-table th{background:#f1f6fb;color:#53657e;text-align:left;padding:4px;border-bottom:1px solid #dfe7f0;white-space:nowrap;font-weight:950}.v133-table td{padding:4px;border-bottom:1px solid #e8edf3;color:#153f79;white-space:nowrap}.v133-table tr:nth-child(even) td{background:#fafcff}.v133-table tr:last-child td{border-bottom:0}.v133-pill{display:inline-block;padding:2px 4px;border-radius:999px;font-size:4.5px;font-weight:950;background:#e7f8ed;color:#128447}.v133-pill.warn{background:#fff2cc;color:#a76b00}.v133-pill.bad{background:#ffe0e4;color:#c92b3c}.v133-pill.info{background:#eaf2ff;color:#1769e8}
.v133-rank{display:grid;grid-template-columns:16px minmax(0,1fr) auto;gap:4px;align-items:center;padding:4px 0;border-bottom:1px solid #edf1f5;font-size:5.5px}.v133-rank:last-child{border-bottom:0}.v133-rank .n{width:15px;height:15px;border-radius:50%;display:grid;place-items:center;background:#e9f2ff;color:#1769e8;font-weight:950}.v133-rank b{color:#173f78}.v133-rank span{color:#6d7b90}.v133-rank strong{color:#0f3975}
.v133-acc{border:1px solid #dfe7f0;border-radius:6px;padding:6px;margin-top:4px}.v133-acc-head{display:flex;gap:5px;align-items:center}.v133-acc-head .garment{font-size:15px}.v133-acc-head h4{margin:0;font-size:7px;color:#173f78}.v133-acc-head p{margin:1px 0 0;font-size:4.5px;color:#748197}.v133-minirow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:3px;margin-top:4px}.v133-mini{border:1px solid #e5ebf3;border-radius:4px;padding:4px}.v133-mini small{display:block;font-size:4px;color:#718096}.v133-mini b{font-size:6px;color:#113d7d}
.v133-alert{display:grid;grid-template-columns:18px minmax(0,1fr);gap:4px;align-items:center;padding:4px 0;border-bottom:1px solid #edf1f5}.v133-alert:last-child{border-bottom:0}.v133-alert .ico{width:17px;height:17px;border-radius:50%;display:grid;place-items:center;background:#eaf2ff;color:#1769e8;font-size:7px;font-weight:950}.v133-alert b{display:block;font-size:5.5px;color:#173f78}.v133-alert span{display:block;font-size:4.5px;color:#748197;margin-top:1px}
.v133-trend{height:72px;display:flex;align-items:end;gap:3px;padding:7px 0 12px}.v133-col{flex:1;min-width:6px;background:#2875ed;border-radius:2px 2px 0 0;position:relative}.v133-col span{position:absolute;bottom:-10px;left:50%;transform:translateX(-50%);font-size:4px;color:#768399}
.v133-compare{margin-top:5px;padding:5px;border:1px solid #d8e8fa;background:#f8fbff;border-radius:5px;font-size:5.5px;color:#244f83}.v133-rules{display:flex;gap:3px;flex-wrap:wrap;margin-top:4px}.v133-rule{padding:3px 4px;border-radius:999px;background:#f3f6fa;color:#51657f;font-size:4.5px;font-weight:850}
.v133-filter-summary{display:flex;gap:3px;flex-wrap:wrap;margin-top:4px}.v133-filter-chip{font-size:4.5px;border:1px solid #d8e4f1;background:#f8fbff;color:#315985;border-radius:999px;padding:2px 4px}
@media(min-width:901px){.v133-shell{gap:9px}.v133-panel{padding:10px}.v133-title{font-size:12px}.v133-sub{font-size:7px}.v133-kpi b{font-size:13px}.v133-table{font-size:7px}.v133-kpis{gap:7px}.v133-grid2{gap:8px}.v133-grid3{gap:7px}.v133-section b{font-size:11px}.v133-filters{max-width:760px}.v133-field select{font-size:9px;height:32px}.v133-query{height:32px;font-size:9px}}
@media(max-width:430px){.v133-shell{gap:5px}.v133-panel{padding:6px}.v133-kpis{grid-template-columns:repeat(3,minmax(0,1fr));gap:3px}.v133-kpi{grid-template-columns:19px minmax(0,1fr);gap:3px;padding:4px;min-height:43px}.v133-icon{width:19px;height:19px;font-size:9px}.v133-kpi b{font-size:8px}.v133-grid2{grid-template-columns:repeat(2,minmax(0,1fr));gap:4px}.v133-grid3{grid-template-columns:repeat(3,minmax(0,1fr));gap:3px}.v133-minirow{grid-template-columns:repeat(5,minmax(0,1fr));gap:2px}.v133-tab{padding:4px 7px;font-size:5.5px}.v133-filters{padding:5px}.v133-field select{height:24px;font-size:6.5px}.v133-query{height:25px}.v133-title{font-size:8.5px}.v133-table{font-size:4.8px}}
</style>'''

    js = r'''<script id="v133-commercial-demo-js">
(function(){
  const isOwner=()=>typeof USER!=='undefined'&&(USER?.role==='superadmin'||USER?.real_role==='superadmin'||USER?.can_preview_roles===true);
  const stores=[
    {name:'Iztapalapa',sale:452610,exist:218500,occ:92.3,ddi:48,util:36.7},
    {name:'Vallejo',sale:438900,exist:211240,occ:89.6,ddi:54,util:38.6},
    {name:'Ecatepec',sale:362450,exist:176340,occ:78.4,ddi:71,util:34.4},
    {name:'Querétaro',sale:358890,exist:159040,occ:74.2,ddi:84,util:35.1},
    {name:'Puebla',sale:298760,exist:146800,occ:69.7,ddi:96,util:31.8},
    {name:'León',sale:276310,exist:128650,occ:63.5,ddi:112,util:30.2}
  ];
  const sections=[
    {name:'Dama',icon:'👗',factor:.47,sug:1012300,exist:612340,occ:86.2},
    {name:'Caballero',icon:'👔',factor:.35,sug:762800,exist:452610,occ:79.4},
    {name:'Infantil',icon:'👕',factor:.18,sug:371220,exist:218500,occ:88.7}
  ];
  const tabs=[['macro','Macro compañía'],['accordion','Acordeón'],['stores','Tiendas'],['sections','Sección / Rubro'],['areas','Ubicación / Área'],['more','Más opciones']];
  const periodFactor={'Sep 2026':1,'Ago 2026':.94,'Jul 2026':.88};
  let active='macro';
  let state={period:'Sep 2026',store:'Compañía',section:'Todas'};
  const fmt=n=>Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:0});
  const money=n=>'$'+fmt(n);
  const selectedStore=()=>stores.find(x=>x.name===state.store);
  function scale(){let f=periodFactor[state.period]||1;const s=selectedStore();if(s)f*=s.sale/452610;const q={Dama:.47,Caballero:.35,Infantil:.18,Lencería:.10}[state.section];if(q)f*=q;return f}
  const scaled=n=>Math.round(Number(n||0)*scale());
  function comparison(){const rank=[...stores].sort((a,b)=>b.sale-a.sale);let name=state.store==='Compañía'?'Iztapalapa':state.store;let i=rank.findIndex(x=>x.name===name);if(i<0)i=0;const j=i===0?1:i-1;return{current:rank[i],comp:rank[j],currentRank:i+1,compRank:j+1}}
  function pill(t,c=''){return `<span class="v133-pill ${c}">${t}</span>`}
  function panel(title,sub,body,link=''){return `<div class="v133-panel"><div class="v133-head"><div><div class="v133-title">${title}</div><div class="v133-sub">${sub||''}</div></div>${link?`<span class="v133-link">${link}</span>`:''}</div>${body}</div>`}
  function kpis(items){return `<div class="v133-kpis">${items.map(x=>`<div class="v133-kpi ${x[4]||''}"><div class="v133-icon">${x[0]}</div><div><small>${x[1]}</small><b>${x[2]}</b><em>${x[3]||''}</em></div></div>`).join('')}</div>`}
  function table(head,rows,wide=false){return `<div class="v133-tablewrap"><table class="v133-table ${wide?'wide':''}"><thead><tr>${head.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(x=>`<td>${x}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function filterMarkup(){return `<div class="v133-filters"><div class="v133-field"><label>Periodo</label><select id="v133Period"><option>Sep 2026</option><option>Ago 2026</option><option>Jul 2026</option></select></div><div class="v133-field"><label>Tienda</label><select id="v133Store"><option>Compañía</option>${stores.map(s=>`<option>${s.name}</option>`).join('')}</select></div><div class="v133-field"><label>Sección</label><select id="v133Section"><option>Todas</option><option>Dama</option><option>Caballero</option><option>Infantil</option><option>Lencería</option></select></div><button type="button" class="v133-query" id="v133Query">Consultar</button></div>`}
  function tabsMarkup(){return `<div class="v133-tabs">${tabs.map(t=>`<button type="button" class="v133-tab" data-v133-tab="${t[0]}">${t[1]}</button>`).join('')}</div>`}
  function macro(){
    const f=scale(),scope=state.store==='Compañía'?'Compañía':state.store;
    const cards=sections.filter(s=>state.section==='Todas'||state.section===s.name).map(s=>`<div class="v133-section"><div class="top"><span class="garment">${s.icon}</span><h4>${s.name}</h4></div><b>${money(Math.round(s.sug*(periodFactor[state.period]||1)*(selectedStore()?selectedStore().sale/452610:1)))}</b><small>Exist. ${fmt(Math.round(s.exist*(periodFactor[state.period]||1)*(selectedStore()?selectedStore().sale/452610:1)))} · Ocup. ${s.occ}%</small></div>`).join('');
    const max=stores[0].sale;const bars=`<div class="v133-bars">${stores.slice(0,5).map(s=>`<div class="v133-bar ${state.store===s.name?'current':''}"><b>${s.name}</b><div class="v133-track"><div class="v133-fill" style="width:${Math.round(s.sale/max*100)}%"></div></div><span>${(s.sale/1000).toFixed(0)}k</span></div>`).join('')}</div>`;
    const sumRows=[['Dama','A',fmt(scaled(612340)),money(scaled(1012300)),'68','86.2%'],['Caballero','B',fmt(scaled(452610)),money(scaled(762800)),'72','79.4%'],['Infantil','A',fmt(scaled(218500)),money(scaled(371220)),'60','88.7%']];
    return `${panel(`Macro compañía · ${state.period}`,`${scope} · ${state.section}`,kpis([['📦','Existencia total',fmt(scaled(1283450)),'pzas'],['🏷','Sugerido compañía',money(scaled(2146320)),'MXN','v133-good'],['🛒','Venta $',money(scaled(1892540)),'MXN','v133-purple'],['%','% Utilidad',(34.8+(f-1)*1.2).toFixed(1)+'%','sobre venta'],['▥','Capacidad · Curva',fmt(scaled(1545000)),'pzas'],['◕','% Ocupación',(83.1+Math.min(5,(f-1)*3)).toFixed(1)+'%','de capacidad']]))}${panel('Macro sección','Sugerido y existencia por sección',`<div class="v133-grid3" style="margin-top:5px">${cards||'<div class="v133-sub">Sección seleccionada disponible en detalle.</div>'}</div>`,'Ver detalle')}<div class="v133-grid2">${panel('Comparativo de tiendas','Venta $ · ranking',bars)}${panel('Macro sección · Compañía','Resumen comercial',table(['Sección','Curva','Exist.','Sugerido','DDI','Ocup.'],sumRows))}</div>${panel('Macro 80/20','Concentración de venta',table(['Nivel','% Part.','Modelos 80%','Modelos 20%'],[['Sección','79.6%','320','80'],['Área','81.2%','410','103'],['Tipo catálogo','77.8%','620','155'],['Macro','83.4%','890','220']]))}`
  }
  function accordion(){
    const visible=sections.filter(s=>state.section==='Todas'||state.section===s.name);const body=visible.map((s,i)=>`<div class="v133-acc"><div class="v133-acc-head"><span class="garment">${s.icon}</span><div style="flex:1"><h4>${s.name}</h4><p>${i===0?'Moda, estilo y tendencia':i===1?'Estilo y funcionalidad':'Moda para su mundo'}</p></div>${pill(i===1?'Atención':'En objetivo',i===1?'warn':'')}</div><div class="v133-minirow"><div class="v133-mini"><small>Sugerido</small><b>${money(scaled(s.sug))}</b></div><div class="v133-mini"><small>Venta</small><b>${money(scaled(s.sug*.82))}</b></div><div class="v133-mini"><small>Utilidad</small><b>${[38.6,32.1,38.5][i]||35}%</b></div><div class="v133-mini"><small>DDI</small><b>${[68,72,60][i]||65}</b></div><div class="v133-mini"><small>Ocup.</small><b>${s.occ}%</b></div></div></div>`).join('');
    return `${panel(`Acordeón comercial · ${state.period}`,`${state.store} · lectura por sección`,body)}<div class="v133-grid2">${panel('Hallazgos clave','',`<div class="v133-alert"><div class="ico">↗</div><div><b>Dama lidera la venta</b><span>Crecimiento y margen favorable.</span></div></div><div class="v133-alert"><div class="ico">✓</div><div><b>Infantil mejora ocupación</b><span>Buena rotación.</span></div></div>`)}${panel('Acciones sugeridas','',`<div class="v133-alert"><div class="ico">◎</div><div><b>Asegurar surtido top</b><span>Mantener disponibilidad.</span></div></div><div class="v133-alert"><div class="ico">!</div><div><b>Revisar Caballero</b><span>Activar acciones selectivas.</span></div></div>`)}</div>`
  }
  function storesPage(){const rows=stores.map((s,i)=>[i+1,`<b>${s.name}</b>`,money(s.sale),fmt(s.exist),s.occ+'%',s.ddi,pill(s.ddi>100?'Riesgo':s.ddi>80?'Atención':'Óptimo',s.ddi>100?'bad':s.ddi>80?'warn':'')]);return `${panel(`Tiendas · ${state.period}`,'Desempeño comercial',kpis([['📦','Existencia',fmt(scaled(1283450)),'pzas'],['🏷','Sugerido',money(scaled(2146320)),'MXN','v133-good'],['🛒','Venta',money(scaled(1892540)),'MXN','v133-purple'],['%','Utilidad','34.8%','sobre venta'],['◷','DDI compañía','68','días'],['◕','Ocupación','83.1%','capacidad']]))}${panel('Ranking de tiendas','Ordenado por venta',table(['#','Tienda','Venta','Exist.','Ocup.','DDI','Estatus'],rows))}${panel('Comparativo visual','Venta por tienda',`<div class="v133-bars">${stores.map(s=>`<div class="v133-bar ${state.store===s.name?'current':''}"><b>${s.name}</b><div class="v133-track"><div class="v133-fill" style="width:${Math.round(s.sale/stores[0].sale*100)}%"></div></div><span>${(s.sale/1000).toFixed(0)}k</span></div>`).join('')}</div>`)}`}
  function sectionsPage(){const sec=state.section==='Todas'?'Dama':state.section;const rub=[['Blusas','A',96340,148200,52,118600,78.4],['Jeans','B',88120,132500,65,102340,71.6],['Vestidos','A',74560,115800,48,96280,81.9],['Playeras','B',92430,120600,71,89450,68.7],['Conjuntos','C',58210,82340,78,56390,64.2]];return `${panel(`Sección / Rubro · ${sec}`,`${state.store} · ${state.period}`,kpis([['📦','Existencia',fmt(scaled(482120)),'pzas'],['🏷','Sugerido 7',money(scaled(672340)),'MXN','v133-good'],['🛒','Venta',money(scaled(514680)),'MXN','v133-purple'],['%','Utilidad','36.2%','sobre venta'],['◷','DDI','61','días'],['◕','Ocupación','82.4%','capacidad']]))}${panel('Detalle de Rubro','Ordenado por venta',table(['Rubro','Curva','Exist.','Sugerido','DDI','Venta','Ocup.'],rub.map(r=>[r[0],r[1],fmt(scaled(r[2])),money(scaled(r[3])),r[4],money(scaled(r[5])),r[6]+'%'])))}<div class="v133-grid2">${panel('Rubros destacados','',`<div class="v133-rank"><span class="n">1</span><div><b>Blusas</b><span>Mayor venta</span></div><strong>${money(scaled(118600))}</strong></div><div class="v133-rank"><span class="n">2</span><div><b>Vestidos</b><span>Alto cumplimiento</span></div><strong>${money(scaled(96280))}</strong></div>`)}${panel('Alertas','',`<div class="v133-alert"><div class="ico">!</div><div><b>Conjuntos</b><span>DDI elevado.</span></div></div><div class="v133-alert"><div class="ico">◷</div><div><b>Playeras</b><span>Revisar rotación.</span></div></div>`)}</div>`}
  function areasPage(){const a=[['Pasillo 1',120,60770,78400,65,81.2],['Pasillo 2',98,53810,72300,72,74.5],['Pasillo 3',86,48600,66200,74,71.3],['Mesa 14',64,30500,41800,68,86.1],['RC 03',48,25400,32700,60,79.4]];return `${panel(`Ubicación / Área · ${state.period}`,`${state.store} · sólo ubicaciones operativas`,kpis([['📦','Existencia',fmt(scaled(452360)),'pzas'],['🏷','Sugerido 7',money(scaled(621840)),'MXN','v133-good'],['🛒','Venta',money(scaled(518430)),'MXN','v133-purple'],['◕','Ocupación','78.6%','capacidad'],['▤','Piso',fmt(scaled(348210)),'pzas'],['▦','Bodega',fmt(scaled(104150)),'pzas']]))}${panel('Detalle por ubicación','Mesa / Pasillo / Ropa Colgada / RC',table(['Ubicación','Modelos','Exist.','Sugerido','DDI','Ocup.'],a.map(r=>[r[0],r[1],fmt(scaled(r[2])),fmt(scaled(r[3])),r[4],r[5]+'%'])))}<div class="v133-grid2">${panel('Distribución por área','',`<div class="v133-bars"><div class="v133-bar"><b>Colgado</b><div class="v133-track"><div class="v133-fill" style="width:85%"></div></div><span>42.5%</span></div><div class="v133-bar"><b>Doblado</b><div class="v133-track"><div class="v133-fill" style="width:57%"></div></div><span>28.3%</span></div><div class="v133-bar"><b>Jeans</b><div class="v133-track"><div class="v133-fill" style="width:37%"></div></div><span>18.6%</span></div></div>`)}${panel('Regla ubicación','',`<div class="v133-alert"><div class="ico">✓</div><div><b>Exhibiciones excluidas</b><span>Cabecera, isla, botadero y similares no cuentan como ubicación operativa.</span></div></div><div class="v133-alert"><div class="ico">▥</div><div><b>Ubicación válida</b><span>Mesa, Pasillo, Ropa Colgada o RC.</span></div></div>`)}</div>`}
  function modelTables(){const c=comparison(),cs=c.current.name,cp=c.comp.name;const slow=[['PS-4312','Blusa manga larga','Dama','Mesa 14','2026-07-18','0.7','0',cp,'8','1.8','2026-08-22','Mesa 11'],['PS-5821','Playera básica','Caballero','Pasillo 7','2026-06-29','0.5','1',cp,'12','2.4','2026-08-30','RC 04'],['PS-7740','Conjunto tejido','Infantil','RC 03','2026-07-05','0.4','0',cp,'6','1.3','2026-08-19','Pasillo 5']];const zero=[['PS-9012','Blusa estampada','Dama','Mesa 09','2026-09-03','0','0',cp,'5','1.2','2026-09-01','Mesa 12'],['PS-5530','Playera cuello redondo','Caballero','RC 08','2026-08-27','0','0',cp,'9','1.6','2026-08-25','RC 02'],['PS-3488','Sudadera infantil','Infantil','Pasillo 4','2026-08-14','0','0',cp,'0','0','2026-08-20','Pasillo 6']];const noLoc=[['PS-7001','Blusa transición','Dama',pill('PRÓXIMO A SALIR','warn'),'86','0','2026-08-02'],['PS-7014','Playera temporada','Caballero',pill('PRÓXIMO A SALIR','warn'),'64','0','2026-07-29'],['PS-8118','Vestido básico','Dama',pill('DESCONTINUADO','bad'),'52','0','2026-06-14'],['PS-8220','Conjunto básico','Infantil',pill('DESCONTINUADO','bad'),'43','0','2026-06-08'],['PS-9301','Blusa impulso','Dama',pill('IMPULSO','info'),'38','0','2026-08-08']];const head=['ID','Modelo','Sección','Ubicación','Últ. entrada tienda','Sug.','Venta 30','Compara','Venta comp.','Sug. comp.','Últ. entrada comp.','Ubicación comp.'];return `${panel('Modelos lentos · ubicación válida','Regla: última entrada >30 días · no exhibiciones',`<div class="v133-rules"><span class="v133-rule">✓ Mesa / Pasillo / Ropa Colgada / RC</span><span class="v133-rule">× Exhibición</span><span class="v133-rule">Entrada >30 días</span></div><div class="v133-compare"><b>${cs} #${c.currentRank}</b> se compara con <b>${cp} #${c.compRank}</b>. Si la consulta es Top 1, se usa Top 2; desde Top 2 se usa la tienda inmediata superior.</div>${table(head,slow.map(r=>r.map((x,i)=>i===8?`${x} ${Number(x)>0?pill('Sí vende'):pill('No vende','bad')}`:x)),true)}`)}${panel('Sugerido 0 · entrada reciente','Regla: sugerido = 0 y última entrada dentro de los últimos 30 días',`${table(head,zero.map(r=>r.map((x,i)=>i===8?`${x} ${Number(x)>0?pill('Sí vende'):pill('No vende','bad')}`:x)),true)}`)}${panel('Modelos sin ubicación','Sugerido 0 · sólo Próximo a salir → Descontinuado → Impulso',`${table(['ID','Modelo','Sección','Estatus catálogo','Exist.','Sugerido','Últ. entrada'],noLoc,true)}`)}`}
  function morePage(){const heights=[35,52,50,65,72,76,85,91,100],months=['Ene','Feb','Mar','Abr','May','Jun','Jul','Ago','Sep'];return `<div class="v133-grid2">${panel('Tendencia mensual','Venta Ene–Sep',`<div class="v133-trend">${heights.map((h,i)=>`<div class="v133-col" style="height:${h}%"><span>${months[i]}</span></div>`).join('')}</div>`)}${panel('Catálogo y estatus','Modelos',`<div class="v133-alert"><div class="ico">✓</div><div><b>Vigente · 1,024</b><span>72.6%</span></div></div><div class="v133-alert"><div class="ico">◷</div><div><b>Próximo a salir · 96</b><span>6.8%</span></div></div><div class="v133-alert"><div class="ico">×</div><div><b>Descontinuado · 182</b><span>12.9%</span></div></div><div class="v133-alert"><div class="ico">↟</div><div><b>Impulso · 108</b><span>7.7%</span></div></div>`)}</div>${modelTables()}`}
  function currentPage(){if(active==='accordion')return accordion();if(active==='stores')return storesPage();if(active==='sections')return sectionsPage();if(active==='areas')return areasPage();if(active==='more')return morePage();return macro()}
  function looksCommercial(){const h=document.getElementById('heroTitle')?.textContent||'';const nav=document.querySelector('.mnav.active,[data-main].active');const dm=nav?.dataset?.main||'';return /Análisis Comercial/i.test(h)||dm==='analysis'||dm==='commercial'}
  function ensureHost(){let host=document.getElementById('v133CommercialDemoHost');if(host)return host;const main=document.querySelector('main.main');if(!main)return null;host=document.createElement('div');host.id='v133CommercialDemoHost';const old=document.getElementById('v132CommercialDemoHost');const nav=document.getElementById('analysisNav');if(old)old.insertAdjacentElement('afterend',host);else if(nav)nav.insertAdjacentElement('afterend',host);else main.appendChild(host);host.addEventListener('click',e=>{const tab=e.target.closest('[data-v133-tab]');if(tab){e.preventDefault();active=tab.dataset.v133Tab;syncTabs();renderContent();return}if(e.target.closest('#v133Query')){e.preventDefault();applyFilters();return}});return host}
  function buildShell(){const host=ensureHost();if(!host)return;host.innerHTML=`<div class="v133-shell">${filterMarkup()}${tabsMarkup()}<div class="v133-note">DEMO · Datos ficticios para validar diseño y navegación. No modifica información real.</div><div id="v133Content" class="v133-content"></div></div>`;host.querySelector('#v133Period').value=state.period;host.querySelector('#v133Store').value=state.store;host.querySelector('#v133Section').value=state.section;syncTabs();renderContent()}
  function syncTabs(){const host=document.getElementById('v133CommercialDemoHost');host?.querySelectorAll('[data-v133-tab]').forEach(b=>b.classList.toggle('active',b.dataset.v133Tab===active))}
  function applyFilters(){const host=document.getElementById('v133CommercialDemoHost');if(!host)return;state.period=host.querySelector('#v133Period')?.value||state.period;state.store=host.querySelector('#v133Store')?.value||state.store;state.section=host.querySelector('#v133Section')?.value||state.section;renderContent()}
  function renderContent(){const content=document.getElementById('v133Content');if(!content)return;content.innerHTML=`<div class="v133-filter-summary"><span class="v133-filter-chip">${state.period}</span><span class="v133-filter-chip">${state.store}</span><span class="v133-filter-chip">${state.section}</span></div>${currentPage()}`;syncTabs()}
  function activate(){if(!isOwner())return;document.body.classList.add('v133-commercial-demo');const h=document.getElementById('heroTitle');if(h)h.innerHTML='Análisis Comercial <span class="v133-badge">DEMO</span>';const s=document.getElementById('heroSub');if(s)s.textContent='Venta, sugerido, utilidad y decisiones comerciales · datos ficticios';const host=ensureHost();if(host&&!host.querySelector('.v133-shell'))buildShell();else if(host){host.style.display='block';syncTabs();renderContent()}}
  function deactivate(){document.body.classList.remove('v133-commercial-demo')}
  document.addEventListener('click',e=>{const main=e.target.closest?.('[data-main]');if(!main)return;const v=main.dataset.main;if(v==='analysis'||v==='commercial')setTimeout(activate,180);else setTimeout(()=>{if(!looksCommercial())deactivate()},200)},true);
  const hero=document.getElementById('heroTitle');if(hero)new MutationObserver(()=>{if(isOwner()&&looksCommercial()&&!document.body.classList.contains('v133-commercial-demo'))setTimeout(activate,80);else if(!looksCommercial())deactivate()}).observe(hero,{childList:true,subtree:true,characterData:true});
  setTimeout(()=>{if(isOwner()&&looksCommercial())activate()},250);setTimeout(()=>{if(isOwner()&&looksCommercial())activate()},900);
  console.info('[V133] Demo Comercial compacto/interactivo listo: filtros y 6 pestañas funcionales.');
})();
</script>'''

    @m.app.middleware("http")
    async def _v133_html(request, call_next):
        response = await call_next(request)
        if request.url.path != "/" or getattr(response, "status_code", 200) != 200:
            return response
        try:
            body = b""
            async for chunk in response.body_iterator:
                body += chunk
            html = body.decode("utf-8", errors="replace")
            if "v133-commercial-demo-js" not in html:
                html = html.replace("</head>", css + "</head>", 1).replace("</body>", js + "</body>", 1)
            return HTMLResponse(html, status_code=response.status_code, headers={
                "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
                "Pragma": "no-cache",
                "Expires": "0",
                "X-Operations-UI-Version": "V133-COMMERCIAL-DEMO-COMPACT",
            })
        except Exception as exc:
            print(f"[V133] HTML warning: {type(exc).__name__}: {exc}", flush=True)
            return response

    m._V133_COMMERCIAL_DEMO_COMPACT = True
    print("[V133] Demo Comercial compacto e interactivo instalado; filtros y pestañas funcionales.", flush=True)
