"""V139 · Análisis Comercial directo en DOM, sin iframe ni carga diferida.

Motivo: Safari/iPhone seguía mostrando el área Comercial en blanco aun cuando
/commercial-demo-v137 respondía 200. Esta capa elimina por completo iframe,
srcdoc, document.write, Blob URL y fetch para el demo del propietario.

El contenido se dibuja directamente en el DOM principal con filtros y 7 pestañas.
También neutraliza visualmente V133–V138 mediante marcadores ocultos, sin tocar
los datos reales ni los módulos operativos.
"""
from __future__ import annotations

from fastapi.responses import HTMLResponse


def install(m):
    if getattr(m, "_V139_COMMERCIAL_DIRECT_DOM", False):
        return

    css = r'''<style id="v139-commercial-direct-css">
body.v139-commercial-direct #v133CommercialDemoHost{display:none!important}
body.v139-commercial-direct #analysisNav,body.v139-commercial-direct #globalFilters,body.v139-commercial-direct #v103FilterShell,body.v139-commercial-direct #v103ClassicBack{display:none!important}
body.v139-commercial-direct main.main>section.page{display:none!important}
#v139CommercialHost{display:none}
body.v139-commercial-direct #v139CommercialHost{display:block!important;position:relative;z-index:2147483647;margin:8px 0 14px;background:#f2f6fb;color:#173f78;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Arial,sans-serif}
#v139CommercialHost *{box-sizing:border-box}
.v139-wrap{display:grid;gap:7px}.v139-filters,.v139-panel{background:#fff;border:1px solid #d9e3ee;border-radius:11px;padding:8px}.v139-filters{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:6px}.v139-field label{display:block;font-size:7px;font-weight:950;color:#687990;margin-bottom:3px;text-transform:uppercase}.v139-field select{width:100%;height:34px;border:1px solid #ccd9e7;border-radius:7px;background:#fff;color:#173f78;padding:4px 7px;font-size:10px;font-weight:850}.v139-query{grid-column:1/-1;height:34px;border:0;border-radius:7px;background:#2f6fe4;color:#fff;font-size:10px;font-weight:950}
.v139-tabs{display:flex;gap:5px;overflow-x:auto;white-space:nowrap;padding:1px 0;-webkit-overflow-scrolling:touch;scrollbar-width:none}.v139-tabs::-webkit-scrollbar{display:none}.v139-tab{flex:0 0 auto;border:1px solid #d4dfec;background:#fff;color:#53657e;border-radius:999px;padding:7px 10px;font-size:8px;font-weight:900;min-height:31px}.v139-tab.active{background:#2f6fe4;color:#fff;border-color:#2f6fe4}.v139-note{padding:7px 9px;border:1px solid #b9d8ff;background:#eef6ff;border-radius:8px;color:#174b85;font-size:7px;font-weight:850}.v139-chips{display:flex;gap:4px;flex-wrap:wrap}.v139-chip{font-size:6px;border:1px solid #d8e4f1;background:#f8fbff;color:#315985;border-radius:999px;padding:3px 6px}
.v139-head{display:flex;justify-content:space-between;gap:6px;align-items:flex-start}.v139-title{font-size:12px;font-weight:950;color:#123b73}.v139-sub{font-size:7px;color:#718096;margin-top:2px}.v139-kpis{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px;margin-top:7px}.v139-kpi{border:1px solid #dfe7f0;border-radius:8px;padding:6px;background:#fff;display:grid;grid-template-columns:24px 1fr;gap:5px;align-items:center;min-height:54px}.v139-ico{width:24px;height:24px;border-radius:50%;display:grid;place-items:center;background:#edf5ff;color:#1769e8;font-size:11px;font-weight:950}.v139-kpi small{display:block;font-size:5.4px;color:#64748b;font-weight:900}.v139-kpi b{display:block;font-size:9.5px;color:#103d7c;margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.v139-kpi em{display:block;font-size:4.8px;color:#8290a2;font-style:normal}.v139-good{background:#effbf4;border-color:#c8ead6}.v139-good b{color:#168447}.v139-purple{background:#f7f3ff;border-color:#ded2ff}.v139-purple b{color:#6030cb}.v139-warn{background:#fff9e9;border-color:#f3e0a8}
.v139-grid2{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:6px}.v139-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:5px}.v139-section{border:1px solid #dfe7f0;border-radius:7px;padding:6px}.v139-section .top{display:flex;align-items:center;gap:5px}.v139-section .garment{font-size:16px}.v139-section h4{font-size:7px;margin:0}.v139-section b{display:block;font-size:9px;margin-top:4px}.v139-section small{display:block;font-size:5.2px;color:#718096;margin-top:2px}.v139-bars{display:grid;gap:4px;margin-top:6px}.v139-bar{display:grid;grid-template-columns:58px minmax(55px,1fr) 42px;gap:4px;align-items:center;font-size:6px}.v139-track{height:9px;background:#e7edf4;border-radius:5px;overflow:hidden}.v139-fill{height:100%;background:#2f72e7;border-radius:5px}.v139-tablewrap{overflow:auto;margin-top:6px;border:1px solid #e3eaf2;border-radius:6px;-webkit-overflow-scrolling:touch}.v139-table{width:100%;border-collapse:collapse;font-size:6px;min-width:420px}.v139-table.wide{min-width:760px}.v139-table th{background:#f1f6fb;color:#53657e;text-align:left;padding:5px;white-space:nowrap}.v139-table td{padding:5px;border-top:1px solid #e8edf3;white-space:nowrap}.v139-pill{display:inline-block;padding:2px 5px;border-radius:999px;font-weight:900;background:#e7f8ed;color:#128447}.v139-pill.mid{background:#fff2cc;color:#a76b00}.v139-pill.bad{background:#ffe0e4;color:#c92b3c}.v139-acc{border:1px solid #dfe7f0;border-radius:7px;padding:7px;margin-top:5px}.v139-minirow{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;margin-top:5px}.v139-mini{border:1px solid #e5ebf3;border-radius:5px;padding:5px}.v139-mini small{display:block;font-size:5px;color:#718096}.v139-mini b{font-size:7px}.v139-alert{display:grid;grid-template-columns:22px 1fr;gap:5px;padding:5px 0;border-bottom:1px solid #edf1f5}.v139-alert:last-child{border-bottom:0}.v139-aico{width:20px;height:20px;border-radius:50%;display:grid;place-items:center;background:#eaf2ff;color:#1769e8;font-size:8px;font-weight:950}.v139-alert b{display:block;font-size:6.5px}.v139-alert span{display:block;font-size:5.3px;color:#748197}.v139-st{display:inline-block;min-width:34px;text-align:center;padding:2px 4px;border-radius:999px;background:#e7f8ed;color:#128447;font-weight:950}.v139-st.mid{background:#fff3d6;color:#9a6a00}.v139-st.low{background:#f1f4f8;color:#5d6f85}.v139-foot{font-size:6px;color:#61758e;margin-top:6px}
@media(max-width:900px){body.v139-commercial-direct .main{padding-bottom:82px!important}body.v139-commercial-direct #v139CommercialHost{margin-top:7px}.v139-wrap{gap:6px}.v139-filters{padding:6px;gap:5px}.v139-field select{height:33px;font-size:9px}.v139-query{height:33px}.v139-tab{font-size:7px;padding:6px 9px}.v139-title{font-size:11px}.v139-kpis{gap:4px}.v139-grid2{gap:4px}.v139-table{font-size:5.5px}}
@media(max-width:430px){.v139-filters{grid-template-columns:repeat(3,minmax(0,1fr));padding:5px;gap:4px}.v139-field label{font-size:6px}.v139-field select{height:32px;font-size:8px;padding:3px 4px}.v139-query{height:32px}.v139-kpis{grid-template-columns:repeat(3,minmax(0,1fr));gap:4px}.v139-kpi{grid-template-columns:20px 1fr;padding:5px;min-height:48px}.v139-ico{width:20px;height:20px;font-size:9px}.v139-kpi b{font-size:8px}.v139-grid2{grid-template-columns:1fr}.v139-grid3{gap:4px}.v139-section .garment{font-size:14px}.v139-minirow{gap:2px}.v139-mini{padding:4px}.v139-tab{font-size:6.5px;padding:6px 8px}}
</style>'''

    js = r'''<script id="v139-commercial-direct-js">
(function(){
  var active='macro';
  var state={period:'Sep 2026',store:'Compañía',section:'Todas'};
  var stores=[
    {n:'Iztapalapa',sale:452610,exist:218500,occ:92.3,ddi:48},{n:'Vallejo',sale:438900,exist:211240,occ:89.6,ddi:54},
    {n:'Ecatepec',sale:362450,exist:176340,occ:78.4,ddi:71},{n:'Querétaro',sale:358890,exist:159040,occ:74.2,ddi:84},
    {n:'Puebla',sale:298760,exist:146800,occ:69.7,ddi:96},{n:'León',sale:276310,exist:128650,occ:63.5,ddi:112}
  ];
  var sections=[{n:'Dama',i:'👗',s:1012300,e:612340,o:86.2},{n:'Caballero',i:'👔',s:762800,e:452610,o:79.4},{n:'Infantil',i:'👕',s:371220,e:218500,o:88.7}];
  var tabs=[['macro','Macro compañía'],['accordion','Acordeón'],['stores','Tiendas'],['sections','Sección / Rubro'],['areas','Ubicación / Área'],['more','Más opciones'],['sell','Sell Through']];
  function owner(){return typeof USER!=='undefined'&&USER&&((USER.role==='superadmin')||(USER.real_role==='superadmin')||(USER.can_preview_roles===true));}
  function commercial(){var a=document.querySelector('[data-main="analysis"].active,[data-main="commercial"].active');var h=(document.getElementById('heroTitle')||{}).textContent||'';return !!a||/Análisis Comercial/i.test(h);}
  function fmt(n){return Number(n||0).toLocaleString('es-MX',{maximumFractionDigits:0});}
  function money(n){return '$'+fmt(n);}
  function factor(){var p={'Sep 2026':1,'Ago 2026':.94,'Jul 2026':.88}[state.period]||1;var s=stores.find(function(x){return x.n===state.store});if(s)p*=s.sale/452610;var q={'Dama':.47,'Caballero':.35,'Infantil':.18,'Lencería':.10}[state.section];if(q)p*=q;return p;}
  function sc(n){return Math.round(Number(n||0)*factor());}
  function pill(t,c){return '<span class="v139-pill '+(c||'')+'">'+t+'</span>';}
  function panel(t,s,b){return '<div class="v139-panel"><div class="v139-head"><div><div class="v139-title">'+t+'</div><div class="v139-sub">'+(s||'')+'</div></div></div>'+b+'</div>';}
  function kpis(items){return '<div class="v139-kpis">'+items.map(function(x){return '<div class="v139-kpi '+(x[4]||'')+'"><div class="v139-ico">'+x[0]+'</div><div><small>'+x[1]+'</small><b>'+x[2]+'</b><em>'+(x[3]||'')+'</em></div></div>';}).join('')+'</div>';}
  function table(h,r,wide){return '<div class="v139-tablewrap"><table class="v139-table '+(wide?'wide':'')+'"><thead><tr>'+h.map(function(x){return '<th>'+x+'</th>';}).join('')+'</tr></thead><tbody>'+r.map(function(row){return '<tr>'+row.map(function(x){return '<td>'+x+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table></div>';}
  function macro(){var cards=sections.filter(function(s){return state.section==='Todas'||state.section===s.n}).map(function(s){return '<div class="v139-section"><div class="top"><span class="garment">'+s.i+'</span><h4>'+s.n+'</h4></div><b>'+money(sc(s.s))+'</b><small>Exist. '+fmt(sc(s.e))+' · Ocup. '+s.o+'%</small></div>';}).join('');var mx=stores[0].sale;var bars='<div class="v139-bars">'+stores.slice(0,5).map(function(s){return '<div class="v139-bar"><b>'+s.n+'</b><div class="v139-track"><div class="v139-fill" style="width:'+Math.round(s.sale/mx*100)+'%"></div></div><span>'+Math.round(s.sale/1000)+'k</span></div>';}).join('')+'</div>';return panel('Macro compañía · '+state.period,state.store+' · '+state.section,kpis([['▣','Existencia total',fmt(sc(1283450)),'pzas'],['🏷','Sugerido compañía',money(sc(2146320)),'MXN','v139-good'],['🛒','Venta $',money(sc(1892540)),'MXN','v139-purple'],['%','% Utilidad','34.8%','sobre venta'],['▥','Capacidad · Curva',fmt(sc(1545000)),'pzas'],['◕','% Ocupación','83.1%','de capacidad']]))+panel('Macro sección','Sugerido y existencia por sección','<div class="v139-grid3" style="margin-top:6px">'+cards+'</div>')+'<div class="v139-grid2">'+panel('Comparativo de tiendas','Venta $ · ranking',bars)+panel('Resumen comercial','Compañía',table(['Sección','Exist.','Sugerido','DDI'],[['Dama',fmt(sc(612340)),money(sc(1012300)),'68'],['Caballero',fmt(sc(452610)),money(sc(762800)),'72'],['Infantil',fmt(sc(218500)),money(sc(371220)),'60']]))+'</div>';}
  function accordion(){var a=sections.filter(function(s){return state.section==='Todas'||state.section===s.n}).map(function(s,i){return '<div class="v139-acc"><div class="top"><span class="garment">'+s.i+'</span><b>'+s.n+'</b></div><div class="v139-minirow"><div class="v139-mini"><small>Sugerido</small><b>'+money(sc(s.s))+'</b></div><div class="v139-mini"><small>Venta</small><b>'+money(sc(s.s*.82))+'</b></div><div class="v139-mini"><small>Utilidad</small><b>'+[38.6,32.1,38.5][i]+'%</b></div><div class="v139-mini"><small>DDI</small><b>'+[68,72,60][i]+'</b></div><div class="v139-mini"><small>Ocup.</small><b>'+s.o+'%</b></div></div></div>';}).join('');return panel('Acordeón comercial · '+state.period,state.store+' · lectura por sección',a)+'<div class="v139-grid2">'+panel('Hallazgos','', '<div class="v139-alert"><div class="v139-aico">↗</div><div><b>Dama lidera la venta</b><span>Margen favorable y buena rotación.</span></div></div>')+panel('Acciones','', '<div class="v139-alert"><div class="v139-aico">◎</div><div><b>Asegurar surtido top</b><span>Mantener disponibilidad de campeones.</span></div></div>')+'</div>';}
  function storesPage(){var rows=stores.map(function(s,i){var c=s.ddi>100?'bad':s.ddi>80?'mid':'';return [i+1,'<b>'+s.n+'</b>',money(Math.round(s.sale*({'Sep 2026':1,'Ago 2026':.94,'Jul 2026':.88}[state.period]||1))),fmt(s.exist),s.occ+'%',s.ddi,pill(s.ddi>100?'Riesgo':s.ddi>80?'Atención':'Óptimo',c)];});return panel('Tiendas · '+state.period,'Desempeño comercial',kpis([['▣','Existencia',fmt(sc(1283450)),'pzas'],['🏷','Sugerido',money(sc(2146320)),'MXN','v139-good'],['🛒','Venta',money(sc(1892540)),'MXN','v139-purple'],['%','Utilidad','34.8%','sobre venta'],['◷','DDI compañía','68','días'],['◕','Ocupación','83.1%','capacidad']]))+panel('Ranking de tiendas','Ordenado por venta',table(['#','Tienda','Venta','Exist.','Ocup.','DDI','Estatus'],rows));}
  function sectionsPage(){var rows=[['Dama','Vestidos',money(sc(426300)),fmt(sc(214200)),'61','38.9%'],['Dama','Blusas',money(sc(318400)),fmt(sc(188420)),'66','37.4%'],['Caballero','Playeras',money(sc(301500)),fmt(sc(176400)),'72','31.8%'],['Infantil','Conjuntos',money(sc(182300)),fmt(sc(98500)),'58','39.2%']];return panel('Sección / Rubro · '+state.period,state.store+' · '+state.section,kpis([['👗','Dama',money(sc(1012300)),'sugerido'],['👔','Caballero',money(sc(762800)),'sugerido'],['👕','Infantil',money(sc(371220)),'sugerido']]))+panel('Detalle de rubros','Macro → micro',table(['Sección','Rubro','Sugerido','Existencia','DDI','% Utilidad'],rows));}
  function areasPage(){var rows=[['Colgado','Pasillo 12',money(sc(286300)),fmt(sc(174200)),'86%'],['Colgado','Pasillo 14',money(sc(241900)),fmt(sc(151400)),'82%'],['Doblado','Mesa 08',money(sc(196500)),fmt(sc(121800)),'79%'],['Jeans','Mesa Jeans 03',money(sc(173800)),fmt(sc(108600)),'91%'],['Lencería','Mueble 05',money(sc(119200)),fmt(sc(76400)),'74%']];return panel('Ubicación / Área · '+state.period,state.store+' · '+state.section,kpis([['↕','Colgado',fmt(sc(540300)),'existencia'],['▤','Doblado',fmt(sc(381900)),'existencia'],['▥','Jeans',fmt(sc(246800)),'existencia'],['◫','Lencería',fmt(sc(114450)),'existencia']]))+panel('Detalle por ubicación','Sugerido mayor a menor',table(['Área','Pasillo / Mesa','Sugerido','Existencia','Ocupación'],rows));}
  function morePage(){return '<div class="v139-grid2">'+panel('Campeones','Modelos con mejor desempeño',table(['ID','Modelo','Sugerido','Venta'],[['MD1023','Vestido Floral',320,294],['MC0876','Playera Polo',410,358],['MI0543','Conjunto Niño',380,323]]))+panel('Lentos','Más de 30 días con ubicación',table(['ID','Modelo','DDI','Checklist'],[['MD0982','Falda Midi',128,'3/4'],['MC0631','Sudadera',142,'2/4'],['MI0715','Pijama',119,'4/4']]))+panel('Sugerido 0','Última entrada ≤ 30 días',table(['ID','Modelo','Últ. entrada','Exist.'],[['MD1102','Chamarra Ligera','08 Sep',62],['MC1201','Camisa Oxford','05 Sep',46]]))+panel('Alertas comerciales','Prioridades sugeridas','<div class="v139-alert"><div class="v139-aico">!</div><div><b>DDI alto en León</b><span>Revisar redistribución y exhibición.</span></div></div><div class="v139-alert"><div class="v139-aico">✓</div><div><b>Iztapalapa en nivel óptimo</b><span>Conservar surtido de campeones.</span></div></div>')+'</div>';}
  function sellPage(){var base=[['92.4%','MD1023','Vestido Floral','Rosa',28,320,420],['89.7%','MD0876','Blusa Básica','Blanco',42,410,280],['85.1%','MD0543','Pantalón Wide','Azul',36,380,350],['78.6%','MD0982','Falda Midi','Beige',52,510,460],['71.9%','MD0715','Jeans Skinny','Azul',68,620,220],['58.7%','MD1102','Chamarra Ligera','Verde',62,720,310]];var rows=base.map(function(r){return [r[0],'<b>'+r[1]+'</b>',r[2],r[3],fmt(Math.max(1,Math.round(r[4]*factor()))),fmt(Math.max(1,Math.round(r[5]*factor()))),money(r[6]),money(Math.max(1,Math.round(r[4]*factor()))*r[6])];});return panel('Sell Through · '+state.period,state.store+' · '+state.section,kpis([['%','Sell Through promedio','79.4%','sobre sugerido'],['▥','Modelos >80%','3','de 6','v139-good'],['◕','Modelos 50–79%','3','de 6','v139-warn'],['$','Inversión total',money(sc(143200)),'MXN','v139-purple']]))+panel('Ranking de modelos por Sell Through','Mayor a menor porcentaje',table(['% Sell Through','ID','Modelo','Color','Existencia','Sugerido','Precio mayoreo','Inversión'],rows,true))+'<div class="v139-foot">Inversión = Precio mayoreo × piezas en existencia</div>';}
  function current(){return active==='macro'?macro():active==='accordion'?accordion():active==='stores'?storesPage():active==='sections'?sectionsPage():active==='areas'?areasPage():active==='more'?morePage():sellPage();}
  function ensureHost(){var h=document.getElementById('v139CommercialHost');if(h)return h;var main=document.querySelector('main.main');if(!main)return null;h=document.createElement('div');h.id='v139CommercialHost';main.appendChild(h);return h;}
  function neutralizeLegacy(){var old=document.getElementById('v133CommercialDemoHost');if(!old)return;['v136CommercialFrame','v137CommercialFrame','v138CommercialFrame'].forEach(function(id){if(!document.getElementById(id)){var d=document.createElement('div');d.id=id;d.style.setProperty('display','none','important');old.appendChild(d);}});}
  function shell(){return '<div class="v139-wrap"><div class="v139-filters"><div class="v139-field"><label>Periodo</label><select id="v139Period"><option>Sep 2026</option><option>Ago 2026</option><option>Jul 2026</option></select></div><div class="v139-field"><label>Tienda</label><select id="v139Store"><option>Compañía</option><option>Iztapalapa</option><option>Vallejo</option><option>Ecatepec</option><option>Querétaro</option><option>Puebla</option><option>León</option></select></div><div class="v139-field"><label>Sección</label><select id="v139Section"><option>Todas</option><option>Dama</option><option>Caballero</option><option>Infantil</option><option>Lencería</option></select></div><button class="v139-query" id="v139Query" type="button">Consultar</button></div><div class="v139-tabs">'+tabs.map(function(t){return '<button class="v139-tab '+(active===t[0]?'active':'')+'" data-v139-tab="'+t[0]+'" type="button">'+t[1]+'</button>';}).join('')+'</div><div class="v139-note">DEMO · Datos ficticios para validar diseño y navegación. No modifica información real.</div><div class="v139-chips"><span class="v139-chip" id="v139ChipPeriod"></span><span class="v139-chip" id="v139ChipStore"></span><span class="v139-chip" id="v139ChipSection"></span></div><div id="v139Content"></div></div>';}
  function draw(){var h=ensureHost();if(!h)return;if(!h.querySelector('.v139-wrap'))h.innerHTML=shell();var p=h.querySelector('#v139Period'),s=h.querySelector('#v139Store'),q=h.querySelector('#v139Section');if(p)p.value=state.period;if(s)s.value=state.store;if(q)q.value=state.section;h.querySelectorAll('[data-v139-tab]').forEach(function(b){b.classList.toggle('active',b.getAttribute('data-v139-tab')===active);});var cp=h.querySelector('#v139ChipPeriod'),cs=h.querySelector('#v139ChipStore'),cq=h.querySelector('#v139ChipSection');if(cp)cp.textContent=state.period;if(cs)cs.textContent=state.store;if(cq)cq.textContent=state.section;var c=h.querySelector('#v139Content');if(c)c.innerHTML=current();}
  function activate(){if(!owner())return;neutralizeLegacy();document.body.classList.add('v139-commercial-direct');var h=document.getElementById('heroTitle');if(h)h.innerHTML='Análisis Comercial <span style="display:inline-flex;margin-left:5px;padding:2px 7px;border-radius:999px;background:#bff3ff;color:#075a7b;font-size:9px;font-weight:950;vertical-align:middle">DEMO</span>';var sub=document.getElementById('heroSub');if(sub)sub.textContent='Venta, sugerido, utilidad y decisiones comerciales · datos ficticios';draw();}
  function deactivate(){document.body.classList.remove('v139-commercial-direct');var h=document.getElementById('v139CommercialHost');if(h)h.style.display='none';}
  document.addEventListener('click',function(e){var main=e.target&&e.target.closest?e.target.closest('[data-main]'):null;if(main){var v=main.getAttribute('data-main');if(v==='analysis'||v==='commercial'){setTimeout(activate,0);setTimeout(activate,120);}else setTimeout(deactivate,120);return;}var tab=e.target&&e.target.closest?e.target.closest('[data-v139-tab]'):null;if(tab){e.preventDefault();active=tab.getAttribute('data-v139-tab')||'macro';draw();return;}if(e.target&&e.target.closest&&e.target.closest('#v139Query')){e.preventDefault();var h=ensureHost();state.period=(h.querySelector('#v139Period')||{}).value||state.period;state.store=(h.querySelector('#v139Store')||{}).value||state.store;state.section=(h.querySelector('#v139Section')||{}).value||state.section;draw();}},true);
  document.addEventListener('change',function(e){if(!document.body.classList.contains('v139-commercial-direct'))return;if(e.target&&e.target.matches&&e.target.matches('#v139Period,#v139Store,#v139Section')){}},true);
  setTimeout(function(){if(owner()&&commercial())activate();},250);setTimeout(function(){if(owner()&&commercial())activate();},800);
  console.info('[V139] Comercial directo en DOM activo; sin iframe, srcdoc, Blob ni fetch.');
})();
</script>'''

    @m.app.middleware("http")
    async def _v139_html(request, call_next):
        response = await call_next(request)
        if request.url.path != "/" or getattr(response, "status_code", 200) != 200:
            return response
        try:
            body = b""
            async for chunk in response.body_iterator:
                body += chunk
            html = body.decode("utf-8", errors="replace")
            if "v139-commercial-direct-js" not in html:
                html = html.replace("</head>", css + "</head>", 1).replace("</body>", js + "</body>", 1)
            return HTMLResponse(html, status_code=response.status_code, headers={
                "Cache-Control": "no-store, no-cache, must-revalidate, max-age=0",
                "Pragma": "no-cache",
                "Expires": "0",
                "X-Operations-UI-Version": "V139-COMMERCIAL-DIRECT-DOM",
            })
        except Exception as exc:
            print(f"[V139] HTML warning: {type(exc).__name__}: {exc}", flush=True)
            return response

    m._V139_COMMERCIAL_DIRECT_DOM = True
    print("[V139] Comercial directo instalado: sin iframe ni carga diferida.", flush=True)
