from __future__ import annotations

from fastapi.responses import HTMLResponse


def install(m):
    if getattr(m, "_V167_FRONTEND", False):
        return

    css = r'''<style id="v167-ui-css">
#logout{display:flex!important;align-items:center!important;justify-content:center!important;gap:7px!important;height:38px!important;min-height:38px!important;max-height:38px!important;margin-top:8px!important;background:#103f7d!important;color:#fff!important;border:1px solid #4a76a8!important;border-radius:9px!important;font-size:9px!important;font-weight:900!important;opacity:1!important;visibility:visible!important}
#logout svg,.v167-icon svg{width:17px;height:17px;display:block;stroke:currentColor;fill:none;stroke-width:1.9;stroke-linecap:round;stroke-linejoin:round}
.v167-tab-icon{display:inline-flex;width:18px;height:18px;align-items:center;justify-content:center;vertical-align:middle;margin-right:5px}.v167-tab-icon svg{width:18px;height:18px}
.profile{overflow:visible!important}.profile:after{display:none!important;content:none!important}
.v161-apply{display:flex!important;align-items:center!important;justify-content:center!important;gap:8px!important}.v161-apply svg{width:18px;height:18px;stroke:#fff!important;fill:none!important;stroke-width:2!important}
.v167-above-avg{color:#d92d20!important;background:#fff0f0!important;border-radius:5px;padding:2px 4px}
.v167-matrix-visual,.v167-sales{background:#fff;border:1px solid #d8e4f0;border-radius:13px;padding:12px;margin:10px 0}
.v167-legend{display:flex;gap:13px;flex-wrap:wrap;font-size:8px;color:#66788f;margin:6px 0 9px}.v167-dot{width:9px;height:9px;border-radius:50%;display:inline-block;margin-right:4px}.v167-m{background:#ec007c}.v167-c{background:#7c3aed}.v167-p{background:#f59e0b}
.v167-hour{display:grid;grid-template-columns:50px repeat(7,minmax(72px,1fr));gap:5px;align-items:center;margin:4px 0;font-size:7px}.v167-track{height:14px;background:#edf2f7;border-radius:6px;overflow:hidden;display:flex}.v167-m,.v167-c,.v167-p{height:100%}
.v167-route-table{max-height:650px;overflow:auto}.v167-route-table .table th{position:sticky;top:0;z-index:3}
.v167-trends{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.v167-trend{border:1px solid #d8e4f0;border-radius:11px;padding:9px}.v167-trend h4{margin:0 0 7px;color:#103f7d;font-size:10px}.v167-trend-row{display:grid;grid-template-columns:45px 1fr 52px;gap:6px;align-items:center;margin:4px 0;font-size:7px}
.v167-chipbar{display:flex;gap:5px;flex-wrap:wrap;margin:5px 0}.v167-chip{border:1px solid #d4e0ed;background:#fff;color:#173f78;border-radius:999px;padding:7px 11px;font-size:8px;font-weight:900;cursor:pointer}.v167-chip.active{background:#176fe8;border-color:#176fe8;color:#fff}
.v166-internal-filter select.v167-hidden,.v166-internal-filter button.v167-hidden{display:none!important}
.v167-sales-head{display:flex;justify-content:space-between;align-items:end;gap:10px;flex-wrap:wrap}.v167-sales-controls{display:flex;gap:6px}.v167-sales-controls select{height:36px;border:1px solid #cbd9e8;border-radius:9px;padding:0 28px 0 9px;color:#173f78;font-weight:850}.v167-sales th button{border:0;background:transparent;color:#fff;font:inherit;font-weight:900;cursor:pointer}.v167-pos{color:#118a52}.v167-neg{color:#d92d20}.v167-rank{font-weight:950}
.v167-safe-tabs{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:5px;margin:8px 0}.v167-safe-tabs button{border:1px solid #d7e1ed;background:#fff;color:#173f78;border-radius:10px;padding:9px;font-size:8px;font-weight:900}.v167-safe-tabs button.active{background:#176fe8;color:#fff}
@media(max-width:900px){.v167-hour{min-width:580px;grid-template-columns:42px repeat(7,68px)}.v167-matrix-visual{overflow:auto}.v167-trends{grid-template-columns:1fr}.v167-safe-tabs{grid-template-columns:repeat(5,120px);overflow:auto}}
</style>'''

    js = r'''<script id="v167-ui-js">
(function(){
if(window.__V167_UI)return;window.__V167_UI=true;
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)],esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const nf=v=>Number(v||0).toLocaleString('es-MX',{maximumFractionDigits:0}),money=v=>'$'+Number(v||0).toLocaleString('es-MX',{maximumFractionDigits:0}),pct=v=>v==null?'—':Number(v).toLocaleString('es-MX',{maximumFractionDigits:1})+'%';
const ico={search:'<svg viewBox="0 0 24 24"><circle cx="10.5" cy="10.5" r="6.5"/><path d="m15.5 15.5 5 5"/></svg>',logout:'<svg viewBox="0 0 24 24"><path d="M10 5H5v14h5M14 8l4 4-4 4M8 12h10"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M4 20V10M10 20V4M16 20v-7M22 20H2"/></svg>',money:'<svg viewBox="0 0 24 24"><path d="M12 3v18M16 7c-1-1-2-1.5-4-1.5-2.3 0-4 1.2-4 3s1.5 2.5 4.3 3.1c2.7.6 4.2 1.4 4.2 3.4 0 2.1-1.9 3.5-4.5 3.5-2 0-3.7-.7-4.8-2"/></svg>',box:'<svg viewBox="0 0 24 24"><path d="M4 7l8-4 8 4-8 4zM4 7v10l8 4 8-4V7M12 11v10"/></svg>',user:'<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4 21c0-4 3.6-7 8-7s8 3 8 7"/></svg>',target:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="4"/><circle cx="12" cy="12" r="1"/></svg>',table:'<svg viewBox="0 0 24 24"><path d="M4 5h16v14H4zM4 10h16M9 5v14M15 5v14"/></svg>',pin:'<svg viewBox="0 0 24 24"><path d="M12 21s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12z"/><circle cx="12" cy="9" r="2"/></svg>',store:'<svg viewBox="0 0 24 24"><path d="M4 10h16l-2-5H6zM5 10v9h14v-9M9 19v-5h6v5"/></svg>',grid:'<svg viewBox="0 0 24 24"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg>',list:'<svg viewBox="0 0 24 24"><path d="M9 6h11M9 12h11M9 18h11M4 6h1M4 12h1M4 18h1"/></svg>',upload:'<svg viewBox="0 0 24 24"><path d="M12 16V4M7 9l5-5 5 5M5 20h14"/></svg>',settings:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19 12a7 7 0 0 0-.1-1l2-1.5-2-3.4-2.4 1A8 8 0 0 0 15 6l-.3-2.6H9.3L9 6a8 8 0 0 0-1.5 1.1l-2.4-1-2 3.4L5.1 11a7 7 0 0 0 0 2l-2 1.5 2 3.4 2.4-1A8 8 0 0 0 9 18l.3 2.6h5.4L15 18a8 8 0 0 0 1.5-1.1l2.4 1 2-3.4-2-1.5a7 7 0 0 0 .1-1z"/></svg>'};
function iconForTab(text){const x=String(text||'').toLowerCase();if(x.includes('recorrido'))return ico.pin;if(x.includes('convers')||x.includes('productiv'))return ico.chart;if(x.includes('recuper'))return ico.money;if(x.includes('carga'))return ico.upload;if(x.includes('meta')||x.includes('estándar')||x.includes('score'))return ico.target;if(x.includes('tienda'))return ico.store;if(x.includes('ubicación')||x.includes('sección')||x.includes('macro'))return ico.grid;if(x.includes('captura')||x.includes('alerta'))return ico.list;return ico.table}
function fixIcons(){
 const b=q('#v161FilterGrid .v161-apply');if(b)b.innerHTML=`<span class="v167-icon">${ico.search}</span><span>Consultar</span>`;
 const lo=q('#logout');if(lo){lo.innerHTML=`<span class="v167-icon">${ico.logout}</span><span>Cerrar sesión</span>`;lo.removeAttribute('style')}
 qa('#operativoNav button,#analysisNav button,.v125-tabs button,.v167-safe-tabs button').forEach(btn=>{const txt=(btn.textContent||'').replace(/\s+/g,' ').trim();btn.querySelectorAll('.v166-tab-icon,.v164-tab-icon,.v167-tab-icon').forEach(x=>x.remove());const s=document.createElement('span');s.className='v167-icon v167-tab-icon';s.innerHTML=iconForTab(txt);btn.prepend(s)});
 qa('.kpi,.report-kpi,.v149-kpi,.v125-kpi').forEach(c=>{c.querySelectorAll('.v166-kpi-icon,.v164-kpi-icon,.v167-card-icon').forEach(x=>x.remove());const lab=(c.querySelector('.lab,.rk-label,small')?.textContent||'').toLowerCase();const code=lab.includes('$')||lab.includes('venta')||lab.includes('recuper')?ico.money:lab.includes('colaborador')?ico.user:lab.includes('meta')||lab.includes('cumpl')?ico.target:lab.includes('pieza')||lab.includes('mercanc')||lab.includes('existencia')||lab.includes('capacidad')?ico.box:ico.chart;const s=document.createElement('span');s.className='v166-kpi-icon v167-card-icon v167-icon';s.innerHTML=code;c.prepend(s)})
}
function chips(){
 qa('.v166-internal-filter').forEach(root=>{const s=root.querySelector('select');if(!s||root.querySelector('.v167-chipbar'))return;const bar=document.createElement('div');bar.className='v167-chipbar';[...s.options].forEach(o=>{const b=document.createElement('button');b.type='button';b.className='v167-chip'+(o.value===s.value?' active':'');b.textContent=o.text;b.onclick=()=>{s.value=o.value;s.dispatchEvent(new Event('change',{bubbles:true}));[...bar.children].forEach(x=>x.classList.toggle('active',x===b))};bar.append(b)});s.classList.add('v167-hidden');root.querySelector('button')?.classList.add('v167-hidden');root.querySelector('.v166-select-wrap')?.append(bar)})
}
function matrixEnhance(){
 const root=q('#v166RoutesMatrix');if(!root)return;const vals=qa('#v166RoutesMatrix .v166-matrix-cell b').map(x=>Number((x.textContent||'').replace(/,/g,''))).filter(x=>x>0),avg=vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:0;
 qa('#v166RoutesMatrix .v166-matrix-cell b').forEach(x=>{const v=Number((x.textContent||'').replace(/,/g,''));x.classList.toggle('v167-above-avg',v>avg&&avg>0)});
 if(root.querySelector('#v167MatrixVisual'))return;const table=root.querySelector('table');if(!table)return;const rows=[...table.querySelectorAll('tbody tr')].map(tr=>{const td=[...tr.children];return{hour:td[0]?.textContent.trim(),cells:td.slice(1,-1).map(cell=>{const t=cell.querySelector('small')?.textContent||'';const get=k=>Number((t.match(new RegExp(k+'\\s*([\\d,]+)'))?.[1]||'0').replace(/,/g,''));return{m:get('M'),c:get('C'),p:get('P')}})}}),mx=Math.max(1,...rows.flatMap(r=>r.cells.map(c=>c.m+c.c+c.p)));
 const box=document.createElement('div');box.id='v167MatrixVisual';box.className='v167-matrix-visual';box.innerHTML=`<b style="color:#103f7d">Distribución por hora y día</b><div class="v167-legend"><span><i class="v167-dot v167-m"></i>Muertos</span><span><i class="v167-dot v167-c"></i>Cajas</span><span><i class="v167-dot v167-p"></i>Probador</span><span>Rojo = arriba del promedio (${nf(avg)} pzas)</span></div>${rows.map(r=>`<div class="v167-hour"><b>${esc(r.hour)}</b>${r.cells.map(c=>`<div class="v167-track"><i class="v167-m" style="width:${c.m/mx*100}%"></i><i class="v167-c" style="width:${c.c/mx*100}%"></i><i class="v167-p" style="width:${c.p/mx*100}%"></i></div>`).join('')}</div>`).join('')}`;root.querySelector('.panel')?.append(box)
}
async function routes(){
 const cont=q('#operativoDynamicContent');if(!cont)return;matrixEnhance();const params=new URLSearchParams({period_type:window.V166_VIEW_TYPE||window.OPER_PERIOD?.type||'week',period_value:window.OPER_PERIOD?.value||q('#operPeriodSelect')?.value||'',store:q('#operStoreSelect')?.value||'Compañía',area:q('#operAreaSelect')?.value||'Todas',activity:q('#operActivitySelect')?.value||'Todas'});
 const boxes=qa('#operativoDynamicContent .chart-box'),rb=boxes.find(x=>(x.querySelector('.chart-title')?.textContent||'').includes('Recorridos por día')),db=boxes.find(x=>(x.querySelector('.chart-title')?.textContent||'').includes('Recolecciones por día')),hb=boxes.find(x=>(x.querySelector('.chart-title')?.textContent||'').includes('Recolecciones por hora'));if(db)db.remove();
 if(rb){try{const d=await api('/api/operations/routes-store-day-v167?'+params,{timeoutMs:90000});rb.innerHTML=`<div class="chart-title">Recorridos por tienda y día</div><div class="tablewrap v167-route-table"><table class="table"><thead><tr><th>Fecha</th><th>Tienda</th><th>Recorridos</th></tr></thead><tbody>${(d.rows||[]).map(r=>`<tr><td>${esc(r.date)}</td><td><b>${esc(r.store)}</b></td><td>${nf(r.routes)}</td></tr>`).join('')||'<tr><td colspan="3">Sin recorridos.</td></tr>'}</tbody></table></div>`}catch(e){rb.innerHTML='<div class="infoempty">'+esc(e.message||e)+'</div>'}}
 if(hb){try{const d=await api('/api/operations/collection-trend-v167?'+params,{timeoutMs:90000});hb.innerHTML=`<div class="chart-title">Tendencia de recolección · ${d.period_type==='day'?'últimos 4 días':d.period_type==='week'?'últimas 4 semanas':d.period_type==='month'?'últimos 4 meses':'acumulado anual'}</div><div class="v167-legend"><span><i class="v167-dot v167-m"></i>Muertos</span><span><i class="v167-dot v167-c"></i>Cajas</span><span><i class="v167-dot v167-p"></i>Probador</span></div><div class="v167-trends">${(d.periods||[]).map(p=>{const mx=Math.max(1,...(p.hours||[]).map(x=>Number(x.total||0)));return`<div class="v167-trend"><h4>${esc(p.label)} · ${nf(p.total)} pzas</h4>${(p.hours||[]).map(x=>`<div class="v167-trend-row"><span>${esc(x.label)}</span><div class="v167-track"><i class="v167-m" style="width:${Number(x.muertos||0)/mx*100}%"></i><i class="v167-c" style="width:${Number(x.cajas||0)/mx*100}%"></i><i class="v167-p" style="width:${Number(x.probador||0)/mx*100}%"></i></div><b>${nf(x.total)}</b></div>`).join('')||'<div class="infoempty">Sin recolección</div>'}</div>`}).join('')}</div>`}catch(e){hb.innerHTML='<div class="infoempty">'+esc(e.message||e)+'</div>'}}
}
async function safeOperation(){
 if(String(window.MAIN||'').toLowerCase()!=='operation'&&document.body.dataset.v163Module!=='operation')return;const cont=q('#operativoDynamicContent');if(!cont)return;q('#operativoDynamic')?.classList.remove('hidden');q('#operativoCentro')?.classList.add('hidden');
 let tabs=cont.querySelector('.v125-tabs,.v167-safe-tabs');if(!tabs){tabs=document.createElement('div');tabs.className='v167-safe-tabs';tabs.innerHTML=[['summary','Resumen'],['daily','Captura diaria'],['capture','Cargar productividad'],['productivity','Productividad'],['standards','Estándares']].map(x=>`<button data-v167-op="${x[0]}">${x[1]}</button>`).join('');cont.prepend(tabs)}
 const active=String(window.V149_OPERATION_TAB||'summary');tabs.querySelectorAll('button').forEach(b=>b.classList.toggle('active',(b.dataset.v167Op||b.dataset.v149Tab||b.dataset.v125Tab)===active));tabs.querySelectorAll('[data-v167-op]').forEach(b=>{if(b.dataset.bound)return;b.dataset.bound='1';b.onclick=async()=>{window.V149_OPERATION_TAB=b.dataset.v167Op;window.V125_OPERATION_TAB=b.dataset.v167Op;if(b.dataset.v167Op==='summary')safeOperation();else window.__V167_RENDER?.('Operación',true)}});
 if(active!=='summary')return;const params=new URLSearchParams({period_type:window.OPER_PERIOD?.type||'week',period_value:window.OPER_PERIOD?.value||q('#operPeriodSelect')?.value||'',store:q('#operStoreSelect')?.value||'Compañía'});
 try{const d=await api('/api/operation/origin-summary-v166?'+params,{timeoutMs:90000});[...cont.children].forEach(x=>{if(x!==tabs)x.remove()});const s=d.summary||{};cont.insertAdjacentHTML('beforeend',`<div class="v149-kpis">${[['Llegada Origen',s.arrival_origin],['Productividad registrada',s.processed],['Mercancía liberada',s.released],['Pendiente',s.pending],['Eficiencia',pct(s.efficiency_pct)],['Prod. promedio',nf(s.productivity_avg)],['Cumplimiento',pct(s.compliance_pct)],['Colaboradores',nf(s.collaborators)],['Colaboradores necesarios',nf(s.required)]].map(x=>`<div class="v149-kpi"><small>${x[0]}</small><b>${typeof x[1]==='number'?nf(x[1]):x[1]}</b></div>`).join('')}</div><div class="v149-panel"><h3>Alertas de Origen</h3>${(d.alerts||[]).map(a=>`<div class="v149-alert ${a.level||'warn'}">${esc(a.text)}</div>`).join('')}</div>`);fixIcons()}catch(e){cont.insertAdjacentHTML('beforeend','<div class="infoempty">No fue posible cargar Operación: '+esc(e.message||e)+'</div>')}
}
function c(v){return v==null?'—':money(v)}function cls(v){return v==null?'':v>=0?'v167-pos':'v167-neg'}
function table(rows,type){const body=q('#v167SalesBody');if(!body)return;window.V167_SORT=window.V167_SORT||{key:'',dir:-1};const arr=[...rows];if(window.V167_SORT.key)arr.sort((a,b)=>(Number(a[window.V167_SORT.key]??-1e99)-Number(b[window.V167_SORT.key]??-1e99))*window.V167_SORT.dir);const store=type==='stores';body.innerHTML=`<div class="tablewrap"><table class="table"><thead><tr><th>#</th><th>${store?'Tienda':'Mes'}</th><th>Meta</th><th>Venta ${window.V167_YEAR}</th><th>Venta ${window.V167_YEAR-1}</th><th>Dif. meta</th><th><button data-sort="pct_goal">% vs meta ↕</button></th><th>Dif. ${window.V167_YEAR-1}</th><th><button data-sort="pct_previous">% vs ${window.V167_YEAR-1} ↕</button></th><th>Venta pzas</th></tr></thead><tbody>${arr.map((r,i)=>`<tr><td class="v167-rank">#${i+1}</td><td><b>${esc(store?r.store:r.label)}</b></td><td>${c(r.target)}</td><td>${money(r.current)}</td><td>${money(r.previous)}</td><td class="${cls(r.diff_goal)}">${c(r.diff_goal)}</td><td class="${cls(r.pct_goal)}">${pct(r.pct_goal)}</td><td class="${cls(r.diff_previous)}">${c(r.diff_previous)}</td><td class="${cls(r.pct_previous)}">${pct(r.pct_previous)}</td><td>${nf(r.pieces)}</td></tr>`).join('')}</tbody></table></div>`;body.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{const k=b.dataset.sort;window.V167_SORT.dir=window.V167_SORT.key===k?-window.V167_SORT.dir:-1;window.V167_SORT.key=k;table(rows,type)})}
async function sales(){
 if(String(window.MAIN||'').toLowerCase()!=='analysis')return;let host=q('#v167Sales');if(!host){const h=[...qa('.title,h2,h3')].find(x=>(x.textContent||'').includes('Ventas · Año vs año pasado'));if(!h)return;host=document.createElement('div');host.id='v167Sales';host.className='v167-sales';(h.closest('.panel')||h.parentElement)?.insertAdjacentElement('afterend',host)}
 window.V167_YEAR=window.V167_YEAR||new Date().getFullYear();window.V167_MONTH=window.V167_MONTH||9;window.V167_STAB=window.V167_STAB||'macro';let d;try{d=await api(`/api/commercial-sales-summary-v167?year=${window.V167_YEAR}&through_month=12`,{timeoutMs:180000})}catch(e){host.innerHTML='<div class="infoempty">'+esc(e.message||e)+'</div>';return}
 host.innerHTML=`<div class="v167-sales-head"><div><b style="font-size:14px;color:#103f7d">Comparativo de ventas</b><div class="v167-chipbar"><button class="v167-chip ${window.V167_STAB==='macro'?'active':''}" data-st="macro">Macro compañía</button><button class="v167-chip ${window.V167_STAB==='stores'?'active':''}" data-st="stores">Tiendas</button></div></div><div class="v167-sales-controls"><select id="v167Year">${(d.available_years||[window.V167_YEAR]).map(y=>`<option ${Number(y)===Number(window.V167_YEAR)?'selected':''}>${y}</option>`).join('')}</select>${window.V167_STAB==='stores'?`<select id="v167Month">${['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((x,i)=>`<option value="${i+1}" ${i+1===window.V167_MONTH?'selected':''}>${x}</option>`).join('')}</select>`:''}</div></div><div id="v167SalesBody"></div>`;
 host.querySelectorAll('[data-st]').forEach(b=>b.onclick=()=>{window.V167_STAB=b.dataset.st;sales()});q('#v167Year')?.addEventListener('change',e=>{window.V167_YEAR=Number(e.target.value);sales()});q('#v167Month')?.addEventListener('change',e=>{window.V167_MONTH=Number(e.target.value);sales()});if(window.V167_STAB==='macro')table(d.months||[],'months');else{let s;try{s=await api(`/api/commercial-sales-stores-v167?year=${window.V167_YEAR}&month=${window.V167_MONTH}`,{timeoutMs:120000})}catch(e){s={rows:[]}}table(s.rows||[],'stores')}
}
function sortZero(){qa('table').forEach(t=>{const hs=[...t.querySelectorAll('thead th')].map(x=>x.textContent.trim()),ix=hs.findIndex(x=>x.includes('Últ. entrada'));if(ix<0||!(t.closest('section,div')?.textContent||'').includes('sugerido 0 a 1'))return;const tb=t.tBodies[0];[...tb.rows].sort((a,b)=>String(a.cells[ix]?.textContent||'9999-12-31').localeCompare(String(b.cells[ix]?.textContent||'9999-12-31'))).forEach(r=>tb.append(r))})}
function after(name){fixIcons();chips();sortZero();if(String(name||'').toLowerCase().includes('recorridos'))setTimeout(routes,30);if(String(name||'')==='Operación')setTimeout(safeOperation,30);if(String(window.MAIN||'').toLowerCase()==='analysis')setTimeout(sales,80)}
if(typeof window.renderOperativoView==='function'){const old=window.renderOperativoView;window.__V167_RENDER=old;window.renderOperativoView=async function(){const r=await old.apply(this,arguments);after(arguments[0]);return r}}
if(typeof window.loadDash==='function'){const old=window.loadDash;window.loadDash=async function(){const r=await old.apply(this,arguments);setTimeout(()=>after('analysis'),20);return r}}
document.addEventListener('click',e=>{if(e.target.closest?.('[data-main="operation"]'))setTimeout(safeOperation,180);if(e.target.closest?.('[data-main="analysis"]'))setTimeout(()=>after('analysis'),220);if(e.target.closest?.('[data-opview="Cumplimiento de Recorridos"]'))setTimeout(routes,180)},true);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{fixIcons();setTimeout(()=>after('boot'),300)});else{fixIcons();setTimeout(()=>after('boot'),250)}
console.info('[V167] UI final instalada.');
})();
</script>'''

    @m.app.middleware("http")
    async def v167_html(request, call_next):
        response = await call_next(request)
        if request.url.path != "/" or getattr(response, "status_code", 200) != 200:
            return response
        try:
            body=b""
            async for chunk in response.body_iterator:
                body+=chunk
            html=body.decode("utf-8",errors="replace")
            if "v167-ui-css" not in html: html=html.replace("</head>",css+"</head>",1)
            if "v167-ui-js" not in html: html=html.replace("</body>",js+"</body>",1)
            headers=dict(getattr(response,"headers",{}) or {}); headers.pop("content-length",None)
            headers.update({"Cache-Control":"no-store, no-cache, must-revalidate, max-age=0","Pragma":"no-cache","Expires":"0","X-Operations-UI-Version":"V167"})
            return HTMLResponse(html,status_code=response.status_code,headers=headers)
        except Exception as exc:
            print(f"[V167-UI] {type(exc).__name__}: {exc}",flush=True)
            return response

    m._V167_FRONTEND = True
    print("[V167-UI] iconos/matriz/recorridos/Operación/ventas instalados.", flush=True)
